// Woordenlijst 4DS LAT – S.O. Groenhove Waregem
// Gebaseerd op de gedrukte woordenlijst 4DS LAT (J.E.)
// Structuur: { grondvorm, aanvullingen, vertaling, repertorium?, thema, tekst, zin }
// repertorium: true = woord gemarkeerd met □ (vet, kernwoordenschat)
// Thema 1: SUPERBIA | Thema 2: HISTORIOGRAFIE

const woordenlijst_4ds = [

  // ══════════════════════════════════════════════════════════════
  // THEMA 1 – SUPERBIA
  // Tekst 1: De vlucht vooruit (p.12)
  // ══════════════════════════════════════════════════════════════

  { grondvorm: "interea", aanvullingen: "bijw.", vertaling: "intussen, ondertussen", repertorium: true, thema: 1, tekst: 1, zin: 183 },
  { grondvorm: "Crete", aanvullingen: "Cretes (v.)", vertaling: "Kreta", thema: 1, tekst: 1, zin: 183 },
  { grondvorm: "perosus", aanvullingen: "perosa, perosum", vertaling: "met haat vervuld", thema: 1, tekst: 1, zin: 183 },
  { grondvorm: "exsilium", aanvullingen: "exsilii (o.)", vertaling: "ballingschap", repertorium: true, thema: 1, tekst: 1, zin: 184 },
  { grondvorm: "tangere", aanvullingen: "tango, tetigi, tactum", vertaling: "aanraken", repertorium: true, thema: 1, tekst: 1, zin: 184 },
  { grondvorm: "locus", aanvullingen: "loci (m.)", vertaling: "plaats, omstandigheid, toestand, gelegenheid", repertorium: true, thema: 1, tekst: 1, zin: 184 },
  { grondvorm: "natalis", aanvullingen: "natalis, natale", vertaling: "van de geboorte, geboorte-", thema: 1, tekst: 1, zin: 184 },
  { grondvorm: "amor", aanvullingen: "amoris (m.)", vertaling: "liefde", repertorium: true, thema: 1, tekst: 1, zin: 184 },
  { grondvorm: "claudere", aanvullingen: "claudo, clausi, clausum", vertaling: "sluiten", repertorium: true, thema: 1, tekst: 1, zin: 185 },
  { grondvorm: "pelagus", aanvullingen: "pelagi (m.)", vertaling: "zee", thema: 1, tekst: 1, zin: 185 },
  { grondvorm: "terra", aanvullingen: "terrae (v.)", vertaling: "aarde, land, streek", repertorium: true, thema: 1, tekst: 1, zin: 185 },
  { grondvorm: "licet", aanvullingen: "+ conj.", vertaling: "al, hoewel", repertorium: true, thema: 1, tekst: 1, zin: 185 },
  { grondvorm: "unda", aanvullingen: "undae (v.)", vertaling: "golf", repertorium: true, thema: 1, tekst: 1, zin: 185 },
  { grondvorm: "obstruere", aanvullingen: "obstruo, obstrūxī, obstrūctum", vertaling: "versperren", thema: 1, tekst: 1, zin: 186 },
  { grondvorm: "at", aanvullingen: "nevensch. vgw.", vertaling: "maar", repertorium: true, thema: 1, tekst: 1, zin: 186 },
  { grondvorm: "caelum", aanvullingen: "caeli (o.)", vertaling: "hemel", repertorium: true, thema: 1, tekst: 1, zin: 186 },
  { grondvorm: "certe", aanvullingen: "bijw.", vertaling: "zeker", repertorium: true, thema: 1, tekst: 1, zin: 186 },
  { grondvorm: "patere", aanvullingen: "pateo, patui, -", vertaling: "1. openstaan; 2. zich uitstrekken", repertorium: true, thema: 1, tekst: 1, zin: 186 },
  { grondvorm: "illac", aanvullingen: "bijw.", vertaling: "daarheen", thema: 1, tekst: 1, zin: 186 },
  { grondvorm: "possidere", aanvullingen: "possideo, possedi, possessum", vertaling: "bezitten", thema: 1, tekst: 1, zin: 187 },
  { grondvorm: "aer", aanvullingen: "aeris (m.)", vertaling: "lucht", repertorium: true, thema: 1, tekst: 1, zin: 187 },
  { grondvorm: "ignotus", aanvullingen: "ignota, ignotum", vertaling: "onbekend", repertorium: true, thema: 1, tekst: 1, zin: 188 },
  { grondvorm: "animum dimittere in", aanvullingen: "", vertaling: "zijn gedachten laten gaan naar, nadenken over", thema: 1, tekst: 1, zin: 188 },
  { grondvorm: "ars", aanvullingen: "artis (v.)", vertaling: "1. kunst; 2. vaardigheid", repertorium: true, thema: 1, tekst: 1, zin: 188 },
  { grondvorm: "novare", aanvullingen: "novo, novavi, novatum", vertaling: "vernieuwen", thema: 1, tekst: 1, zin: 189 },
  { grondvorm: "nam", aanvullingen: "nevensch. vgw.", vertaling: "want", repertorium: true, thema: 1, tekst: 1, zin: 189 },
  { grondvorm: "ponere", aanvullingen: "pono, posui, positum", vertaling: "plaatsen, leggen", repertorium: true, thema: 1, tekst: 1, zin: 189 },
  { grondvorm: "ordo", aanvullingen: "ordinis (m.)", vertaling: "rij, rang, orde, stand", repertorium: true, thema: 1, tekst: 1, zin: 189 },
  { grondvorm: "penna", aanvullingen: "pennae (v.)", vertaling: "1. veer, slagpen; 2. vleugel", repertorium: true, thema: 1, tekst: 1, zin: 189 },
  { grondvorm: "coepisse", aanvullingen: "coepi of coeptus sum", vertaling: "beginnen", repertorium: true, thema: 1, tekst: 1, zin: 190 },
  { grondvorm: "brevis", aanvullingen: "brevis, breve", vertaling: "kort", repertorium: true, thema: 1, tekst: 1, zin: 190 },
  { grondvorm: "sequi", aanvullingen: "sequor, secutus sum", vertaling: "volgen", repertorium: true, thema: 1, tekst: 1, zin: 190 },
  { grondvorm: "clivus", aanvullingen: "clivi (m.)", vertaling: "helling", thema: 1, tekst: 1, zin: 191 },
  { grondvorm: "crescere", aanvullingen: "cresco, crevi, cretum", vertaling: "groeien", repertorium: true, thema: 1, tekst: 1, zin: 191 },
  { grondvorm: "putare", aanvullingen: "puto, putavi, putatum", vertaling: "1. menen, denken, geloven; 2. schatten, (waard) achten", repertorium: true, thema: 1, tekst: 1, zin: 191 },
  { grondvorm: "rusticus", aanvullingen: "rustica, rusticum", vertaling: "landelijk", thema: 1, tekst: 1, zin: 191 },
  { grondvorm: "quondam", aanvullingen: "bijw.", vertaling: "1. eens, ooit; 2. soms", repertorium: true, thema: 1, tekst: 1, zin: 191 },
  { grondvorm: "fistula", aanvullingen: "fistulae (v.)", vertaling: "herdersfluit", thema: 1, tekst: 1, zin: 192 },
  { grondvorm: "dispar", aanvullingen: "dispar, dispar gen. disparis", vertaling: "ongelijk", thema: 1, tekst: 1, zin: 192 },
  { grondvorm: "paulatim", aanvullingen: "bijw.", vertaling: "geleidelijk, langzamerhand", repertorium: true, thema: 1, tekst: 1, zin: 192 },
  { grondvorm: "surgere", aanvullingen: "surgo, surrexi, surrectum", vertaling: "1. opstaan, opstijgen; 2. ontstaan", repertorium: true, thema: 1, tekst: 1, zin: 192 },
  { grondvorm: "avena", aanvullingen: "avenae (v.)", vertaling: "rietstengel", thema: 1, tekst: 1, zin: 192 },

  // ── Tekst 2: Genie aan het werk (p.18) ──

  { grondvorm: "tum", aanvullingen: "bijw.", vertaling: "1. toen, op dat moment; 2. daarna, vervolgens", repertorium: true, thema: 1, tekst: 2, zin: 193 },
  { grondvorm: "linum", aanvullingen: "lini (o.)", vertaling: "vlas, koord", thema: 1, tekst: 2, zin: 193 },
  { grondvorm: "cera", aanvullingen: "cerae (v.)", vertaling: "was", thema: 1, tekst: 2, zin: 193 },
  { grondvorm: "alligare", aanvullingen: "alligo, alligavi, alligatum", vertaling: "vastbinden, vastmaken", thema: 1, tekst: 2, zin: 193 },
  { grondvorm: "imus", aanvullingen: "ima, imum", vertaling: "onderste, laagste (hier: onderaan)", thema: 1, tekst: 2, zin: 193 },
  { grondvorm: "ita", aanvullingen: "bijw.", vertaling: "zo", repertorium: true, thema: 1, tekst: 2, zin: 194 },
  { grondvorm: "componere", aanvullingen: "compono, composui, compositum", vertaling: "1. samenstellen; 2. veinzen", repertorium: true, thema: 1, tekst: 2, zin: 194 },
  { grondvorm: "parvus", aanvullingen: "parva, parvum", vertaling: "klein", repertorium: true, thema: 1, tekst: 2, zin: 194 },
  { grondvorm: "curvamen", aanvullingen: "curvaminis (o.)", vertaling: "kromming, welving", thema: 1, tekst: 2, zin: 194 },
  { grondvorm: "flectere", aanvullingen: "flecto, flexi, flexum", vertaling: "1. buigen, ombuigen; 2. vermurwen", repertorium: true, thema: 1, tekst: 2, zin: 194 },
  { grondvorm: "ut", aanvullingen: "+ conj.", vertaling: "dat, zodat, opdat, om te", repertorium: true, thema: 1, tekst: 2, zin: 195 },
  { grondvorm: "verus", aanvullingen: "vera, verum", vertaling: "echt, waar", repertorium: true, thema: 1, tekst: 2, zin: 195 },
  { grondvorm: "imitari", aanvullingen: "imitor, imitatus sum", vertaling: "nabootsen", thema: 1, tekst: 2, zin: 195 },
  { grondvorm: "avis", aanvullingen: "avis (v.)", vertaling: "vogel", repertorium: true, thema: 1, tekst: 2, zin: 195 },
  { grondvorm: "una", aanvullingen: "bijw.", vertaling: "samen, tegelijk", repertorium: true, thema: 1, tekst: 2, zin: 195 },
  { grondvorm: "ignarus", aanvullingen: "ignara, ignarum + gen.", vertaling: "onervaren, onwetend", repertorium: true, thema: 1, tekst: 2, zin: 196 },
  { grondvorm: "tractare", aanvullingen: "tracto, tractavi, tractatum", vertaling: "1. (rond)slepen, (mee)sleuren; 2. behandelen, bewerken", repertorium: true, thema: 1, tekst: 2, zin: 196 },
  { grondvorm: "periculum", aanvullingen: "periculi (o.)", vertaling: "gevaar, risico", repertorium: true, thema: 1, tekst: 2, zin: 196 },
  { grondvorm: "os", aanvullingen: "oris (o.)", vertaling: "1. mond, muil, bek; 2. gezicht, gelaat", repertorium: true, thema: 1, tekst: 2, zin: 197 },
  { grondvorm: "renidere", aanvullingen: "renideo, -, -", vertaling: "glanzen, glimlachen", thema: 1, tekst: 2, zin: 197 },
  { grondvorm: "modo … modo", aanvullingen: "", vertaling: "nu eens … dan weer", thema: 1, tekst: 2, zin: 197 },
  { grondvorm: "vagus", aanvullingen: "vaga, vagum", vertaling: "zwervend, vluchtig; speels", thema: 1, tekst: 2, zin: 197 },
  { grondvorm: "movere", aanvullingen: "moveo, movi, motum", vertaling: "1. bewegen; 2. ontroeren", repertorium: true, thema: 1, tekst: 2, zin: 197 },
  { grondvorm: "aura", aanvullingen: "aurae (v.)", vertaling: "1. bries, wind; 2. lucht", repertorium: true, thema: 1, tekst: 2, zin: 197 },
  { grondvorm: "captare", aanvullingen: "capto, captavi, captatum", vertaling: "gretig grijpen naar, trachten te vangen", thema: 1, tekst: 2, zin: 198 },
  { grondvorm: "pluma", aanvullingen: "plumae (v.)", vertaling: "pluim", repertorium: true, thema: 1, tekst: 2, zin: 198 },
  { grondvorm: "flavus", aanvullingen: "flava, flavum", vertaling: "goud, goudgeel", thema: 1, tekst: 2, zin: 198 },
  { grondvorm: "pollex", aanvullingen: "pollicis (m.)", vertaling: "duim", thema: 1, tekst: 2, zin: 198 },
  { grondvorm: "mollire", aanvullingen: "mollio, molivi, molitum", vertaling: "week, zacht, soepel maken", thema: 1, tekst: 2, zin: 199 },
  { grondvorm: "lusus", aanvullingen: "lusus (m.)", vertaling: "spel", thema: 1, tekst: 2, zin: 199 },
  { grondvorm: "suus", aanvullingen: "sua, suum", vertaling: "zijn, haar", repertorium: true, thema: 1, tekst: 2, zin: 199 },
  { grondvorm: "mirabilis", aanvullingen: "mirabilis, mirabile", vertaling: "verwonderlijk, verbazingwekkend", thema: 1, tekst: 2, zin: 199 },
  { grondvorm: "pater", aanvullingen: "patris (m.)", vertaling: "vader", repertorium: true, thema: 1, tekst: 2, zin: 199 },
  { grondvorm: "impedire", aanvullingen: "impedio, impedivi, impeditum", vertaling: "verhinderen, belemmeren", repertorium: true, thema: 1, tekst: 2, zin: 200 },
  { grondvorm: "opus", aanvullingen: "operis (o.)", vertaling: "werk, moeite", repertorium: true, thema: 1, tekst: 2, zin: 200 },
  { grondvorm: "postquam", aanvullingen: "(vgw.) (+ind. perf.)", vertaling: "nadat", repertorium: true, thema: 1, tekst: 2, zin: 200 },
  { grondvorm: "manus", aanvullingen: "manus (v.)", vertaling: "1. hand, handvol; 2. troep", repertorium: true, thema: 1, tekst: 2, zin: 200 },
  { grondvorm: "ultimus", aanvullingen: "ultima, ultimum", vertaling: "verst verwijderd, uiterst, laatst", thema: 1, tekst: 2, zin: 200 },
  { grondvorm: "imponere", aanvullingen: "impono, imposui, impositum", vertaling: "plaatsen, leggen in/op, opleggen", repertorium: true, thema: 1, tekst: 2, zin: 201 },
  { grondvorm: "geminus", aanvullingen: "gemina, geminum", vertaling: "dubbel, tweeling-", repertorium: true, thema: 1, tekst: 2, zin: 201 },
  { grondvorm: "opifex", aanvullingen: "opificis (m.)", vertaling: "bouwer, vervaardiger, maker", thema: 1, tekst: 2, zin: 201 },
  { grondvorm: "librare", aanvullingen: "libro, libravi, libratum", vertaling: "in evenwicht houden of brengen", thema: 1, tekst: 2, zin: 201 },
  { grondvorm: "ala", aanvullingen: "alae (v.)", vertaling: "vleugel", repertorium: true, thema: 1, tekst: 2, zin: 201 },
  { grondvorm: "ipse", aanvullingen: "ipsa, ipsum", vertaling: "zelf", repertorium: true, thema: 1, tekst: 2, zin: 202 },
  { grondvorm: "corpus", aanvullingen: "corporis (o.)", vertaling: "lichaam", repertorium: true, thema: 1, tekst: 2, zin: 202 },
  { grondvorm: "pendere", aanvullingen: "pendeo, pependi, -", vertaling: "hangen", repertorium: true, thema: 1, tekst: 2, zin: 202 },

  // ── Tekst 3: Een bezorgde vader (p.26) ──
  // (zinsnummers volgens de PDF-nummering)

  { grondvorm: "excipere", aanvullingen: "excipio, excepi, exceptum", vertaling: "1. uitnemen, uittrekken; 2. opvangen, opnemen", repertorium: true, thema: 1, tekst: 3, zin: 230 },
  { grondvorm: "trahere", aanvullingen: "traho, traxi, tractum", vertaling: "trekken, slepen, sleuren", repertorium: true, thema: 1, tekst: 3, zin: 230 },
  { grondvorm: "ille", aanvullingen: "illa, illud", vertaling: "die, dat", repertorium: true, thema: 1, tekst: 3, zin: 230 },
  { grondvorm: "infelix", aanvullingen: "infelix, infelix (gen. infelicis)", vertaling: "ongelukkig", thema: 1, tekst: 3, zin: 231 },
  { grondvorm: "iam", aanvullingen: "bijw.", vertaling: "al, reeds, nu, dadelijk", repertorium: true, thema: 1, tekst: 3, zin: 231 },
  { grondvorm: "ubi", aanvullingen: "bijw.", vertaling: "waar", repertorium: true, thema: 1, tekst: 3, zin: 232 },
  { grondvorm: "regio", aanvullingen: "regionis (v.)", vertaling: "streek, gebied", repertorium: true, thema: 1, tekst: 3, zin: 232 },
  { grondvorm: "requirere", aanvullingen: "requiro, requisivi, requisitum", vertaling: "zoeken, navragen", thema: 1, tekst: 3, zin: 232 },
  { grondvorm: "aspicere", aanvullingen: "aspicio, aspexi, aspectum", vertaling: "kijken naar, aankijken", repertorium: true, thema: 1, tekst: 3, zin: 233 },
  { grondvorm: "devovere", aanvullingen: "devoveo, devovi, devotum", vertaling: "aan een godheid wijden; (hier: vervloeken)", thema: 1, tekst: 3, zin: 234 },
  { grondvorm: "sepulcrum", aanvullingen: "sepulcri (o.)", vertaling: "graf(tombe)", thema: 1, tekst: 3, zin: 234 },
  { grondvorm: "condere", aanvullingen: "condo, condidi, conditum", vertaling: "1. stichten; 2. opbergen", repertorium: true, thema: 1, tekst: 3, zin: 235 },
  { grondvorm: "tellus", aanvullingen: "telluris (v.)", vertaling: "aarde, land, streek, gebied", repertorium: true, thema: 1, tekst: 3, zin: 235 },
  { grondvorm: "sepelire", aanvullingen: "sepelio, sepelivi, sepultum", vertaling: "begraven", thema: 1, tekst: 3, zin: 235 },

  // ── Tekst 4: Een brug te ver? (p.46) ──

  { grondvorm: "totus", aanvullingen: "tota, totum", vertaling: "geheel", repertorium: true, thema: 1, tekst: 4, zin: 9 },
  { grondvorm: "fere", aanvullingen: "bijw.", vertaling: "bijna, ongeveer", repertorium: true, thema: 1, tekst: 4, zin: 9 },
  { grondvorm: "nasci", aanvullingen: "nascor, natus sum", vertaling: "geboren worden, afstammen van", repertorium: true, thema: 1, tekst: 4, zin: 9 },
  { grondvorm: "subdere", aanvullingen: "subdo, subdidi, subditum", vertaling: "blootstellen, leggen onder", thema: 1, tekst: 4, zin: 9 },
  { grondvorm: "Phoebus", aanvullingen: "Phoebi (m.)", vertaling: "Apollo", thema: 1, tekst: 4, zin: 9 },
  { grondvorm: "Eous", aanvullingen: "Eoa, Eoum", vertaling: "oosters", thema: 1, tekst: 4, zin: 10 },
  { grondvorm: "spectare", aanvullingen: "specto, spectavi, spectatum", vertaling: "bekijken", repertorium: true, thema: 1, tekst: 4, zin: 10 },
  { grondvorm: "audax", aanvullingen: "audax, audax, gen. audacis", vertaling: "dapper", thema: 1, tekst: 4, zin: 10 },
  { grondvorm: "vertex", aanvullingen: "verticis (v.)", vertaling: "1. draaikolk; 2. wervelwind; 3. kruin, top", repertorium: true, thema: 1, tekst: 4, zin: 10 },
  { grondvorm: "tractus", aanvullingen: "tractus (m.)", vertaling: "regio, streek", thema: 1, tekst: 4, zin: 10 },
  { grondvorm: "pars", aanvullingen: "partis (v.)", vertaling: "deel, zijde", repertorium: true, thema: 1, tekst: 4, zin: 11 },
  { grondvorm: "situs", aanvullingen: "situs (m.)", vertaling: "plaats", thema: 1, tekst: 4, zin: 11 },
  { grondvorm: "Libye", aanvullingen: "Libyes (v.)", vertaling: "Libië", thema: 1, tekst: 4, zin: 11 },
  { grondvorm: "despectare", aanvullingen: "despecto, despectavi, despectatum", vertaling: "naar beneden kijken", thema: 1, tekst: 4, zin: 11 },
  { grondvorm: "auster", aanvullingen: "austri (m.)", vertaling: "zuiden, zuidenwind", repertorium: true, thema: 1, tekst: 4, zin: 11 },
  { grondvorm: "altus", aanvullingen: "alta, altum", vertaling: "1. hoog; 2. diep", repertorium: true, thema: 1, tekst: 4, zin: 12 },
  { grondvorm: "erigere", aanvullingen: "erigo, erexi, erectum", vertaling: "omhoog richten, oprichten", thema: 1, tekst: 4, zin: 12 },
  { grondvorm: "aether", aanvullingen: "aetheris (m.)", vertaling: "hemel, lucht", repertorium: true, thema: 1, tekst: 4, zin: 12 },
  { grondvorm: "tendere", aanvullingen: "tendo, tetendi, tentum of tensum", vertaling: "spannen, streven naar, gaan", repertorium: true, thema: 1, tekst: 4, zin: 12 },
  { grondvorm: "ceterus", aanvullingen: "cetera, ceterum", vertaling: "overig", repertorium: true, thema: 1, tekst: 4, zin: 12 },
  { grondvorm: "planum", aanvullingen: "plani (o.)", vertaling: "vlakte", thema: 1, tekst: 4, zin: 13 },
  { grondvorm: "iacere", aanvullingen: "iaceo, iacui, -", vertaling: "liggen", repertorium: true, thema: 1, tekst: 4, zin: 13 },
  { grondvorm: "nomen", aanvullingen: "nominis (o.)", vertaling: "naam", repertorium: true, thema: 1, tekst: 4, zin: 13 },
  { grondvorm: "se", aanvullingen: "wederkerend vnw.", vertaling: "zich, elkaar; hij, zij, het, ze (in ACI-zinnen)", repertorium: true, thema: 1, tekst: 4, zin: 13 },
  { grondvorm: "Caucasus", aanvullingen: "Caucasi (m.)", vertaling: "de Kaukasus", thema: 1, tekst: 4, zin: 14 },
  { grondvorm: "emittere", aanvullingen: "emitto, emisi, emissum", vertaling: "wegsturen, wegzenden", thema: 1, tekst: 4, zin: 14 },
  { grondvorm: "rapidus", aanvullingen: "rapida, rapidum", vertaling: "snel", thema: 1, tekst: 4, zin: 14 },
  { grondvorm: "occursus", aanvullingen: "occursus (m.)", vertaling: "ontmoeting", thema: 1, tekst: 4, zin: 14 },
  { grondvorm: "amnis", aanvullingen: "amnis (m.)", vertaling: "rivier, stroom", repertorium: true, thema: 1, tekst: 4, zin: 14 },
  { grondvorm: "reliquus", aanvullingen: "reliqua, reliquum", vertaling: "overig", repertorium: true, thema: 1, tekst: 4, zin: 15 },
  { grondvorm: "sortiri", aanvullingen: "sortior, sortitus sum", vertaling: "1. krijgen; 2. toebedelen", thema: 1, tekst: 4, zin: 15 },
  { grondvorm: "India", aanvullingen: "Indiae (v.)", vertaling: "India", thema: 1, tekst: 4, zin: 15 },
  { grondvorm: "Indus", aanvullingen: "Indi (m.)", vertaling: "de Indus, rivier in India", thema: 1, tekst: 4, zin: 16 },
  { grondvorm: "frigidus", aanvullingen: "frigida, frigidum", vertaling: "koel, koud, kil", repertorium: true, thema: 1, tekst: 4, zin: 16 },
  { grondvorm: "australis", aanvullingen: "australis, australe", vertaling: "zuiders", thema: 1, tekst: 4, zin: 16 },
  { grondvorm: "iugosus", aanvullingen: "iugosa, iugosum", vertaling: "bergachtig", thema: 1, tekst: 4, zin: 16 },
  { grondvorm: "mons", aanvullingen: "montis (m.)", vertaling: "berg", repertorium: true, thema: 1, tekst: 4, zin: 17 },
  { grondvorm: "invehere", aanvullingen: "inveho, invexi, invectum", vertaling: "inbrengen, invoeren", thema: 1, tekst: 4, zin: 17 },
  { grondvorm: "directus", aanvullingen: "directa, directum", vertaling: "recht", thema: 1, tekst: 4, zin: 17 },
  { grondvorm: "gurges", aanvullingen: "gurgitis (m.)", vertaling: "draaikolk, stroom", thema: 1, tekst: 4, zin: 17 },
  { grondvorm: "Ganges", aanvullingen: "Gangis (m.)", vertaling: "de Ganges, rivier in India", thema: 1, tekst: 4, zin: 17 },

  // ── Tekst 4: Een brug te ver? (p.48) ──

  { grondvorm: "fluvius", aanvullingen: "fluvii (m.)", vertaling: "stroom, rivier", thema: 1, tekst: 4, zin: 18 },
  { grondvorm: "Oriens", aanvullingen: "Orientis (m.)", vertaling: "het oosten", thema: 1, tekst: 4, zin: 18 },
  { grondvorm: "uterque", aanvullingen: "utraque, utrumque", vertaling: "elk van beide(n), beide(n)", repertorium: true, thema: 1, tekst: 4, zin: 18 },
  { grondvorm: "turbidus", aanvullingen: "turbida, turbidum", vertaling: "woest, onrustig", thema: 1, tekst: 4, zin: 19 },
  { grondvorm: "extendere", aanvullingen: "extendo, extendi, extensum", vertaling: "uitstrekken", thema: 1, tekst: 4, zin: 19 },
  { grondvorm: "verberare", aanvullingen: "verbero, verberavi, verberatum", vertaling: "slaan", thema: 1, tekst: 4, zin: 19 },
  { grondvorm: "robur", aanvullingen: "roboris (o.)", vertaling: "eik, boom", thema: 1, tekst: 4, zin: 20 },
  { grondvorm: "solum", aanvullingen: "soli (o.)", vertaling: "bodem, grond", repertorium: true, thema: 1, tekst: 4, zin: 20 },
  { grondvorm: "radicitus", aanvullingen: "bijw.", vertaling: "door en door", thema: 1, tekst: 4, zin: 20 },
  { grondvorm: "eruere", aanvullingen: "eruo, eruti, erutum", vertaling: "loswrikken", thema: 1, tekst: 4, zin: 20 },
  { grondvorm: "absorbere", aanvullingen: "absorbeo, absorbui, -", vertaling: "1. verslinden; 2. opslokken", repertorium: true, thema: 1, tekst: 4, zin: 21 },
  { grondvorm: "si", aanvullingen: "+ ind/conj.", vertaling: "indien, als", repertorium: true, thema: 1, tekst: 4, zin: 21 },
  { grondvorm: "fortis", aanvullingen: "fortis, forte", vertaling: "sterk, dapper", repertorium: true, thema: 1, tekst: 4, zin: 21 },
  { grondvorm: "mollis", aanvullingen: "mollis, molle", vertaling: "zacht, week", repertorium: true, thema: 1, tekst: 4, zin: 22 },
  { grondvorm: "reperire", aanvullingen: "reperio, repperi, repertum", vertaling: "1. vinden, aantreffen; 2. uitvinden", repertorium: true, thema: 1, tekst: 4, zin: 22 },
  { grondvorm: "stagnare", aanvullingen: "stagno, stagnavi, stagnatum", vertaling: "stilstaan", thema: 1, tekst: 4, zin: 22 },
  { grondvorm: "fluere", aanvullingen: "fluo, fluxi, fluxum/fluctum", vertaling: "vloeien, stromen", thema: 1, tekst: 4, zin: 22 },
  { grondvorm: "insula", aanvullingen: "insulae (v.)", vertaling: "eiland", thema: 1, tekst: 4, zin: 23 },
  { grondvorm: "bibere", aanvullingen: "bibo, bibi, -", vertaling: "drinken", thema: 1, tekst: 4, zin: 23 },
  { grondvorm: "intercipere", aanvullingen: "intercipio, intercepi, interceptum", vertaling: "onderscheppen", thema: 1, tekst: 4, zin: 23 },
  { grondvorm: "mare", aanvullingen: "maris (o.)", vertaling: "zee", repertorium: true, thema: 1, tekst: 4, zin: 23 },
  { grondvorm: "decurrere", aanvullingen: "decurro, decurri, decursum", vertaling: "naar beneden lopen", thema: 1, tekst: 4, zin: 24 },
  { grondvorm: "Achesis", aanvullingen: "Achesis (m.)", vertaling: "de Achesis, rivier in India", thema: 1, tekst: 4, zin: 24 },
  { grondvorm: "occurrere", aanvullingen: "occurro, occurri, occursum + dat.", vertaling: "tegemoetkomen, oprukken tegen", repertorium: true, thema: 1, tekst: 4, zin: 24 },
  { grondvorm: "collidere", aanvullingen: "collido, collisi, collisum", vertaling: "botsen", thema: 1, tekst: 4, zin: 24 },
  { grondvorm: "aestus", aanvullingen: "aestus (m.)", vertaling: "1. hitte, gloed; 2. golf, branding", repertorium: true, thema: 1, tekst: 4, zin: 24 },
  { grondvorm: "motus", aanvullingen: "motus (m.)", vertaling: "beweging", repertorium: true, thema: 1, tekst: 4, zin: 25 },

  // ── Tekst 5: De uitdager (p.52) ──

  { grondvorm: "iam", aanvullingen: "bijw.", vertaling: "al, reeds", repertorium: true, thema: 1, tekst: 5, zin: 291 },
  { grondvorm: "credere", aanvullingen: "credo, credidi, creditum (+dat.)", vertaling: "geloven, vertrouwen", repertorium: true, thema: 1, tekst: 5, zin: 291 },
  { grondvorm: "Avernus", aanvullingen: "Averni (m.)", vertaling: "de onderwereld", thema: 1, tekst: 5, zin: 291 },
  { grondvorm: "immiscere", aanvullingen: "immisceo, immiscui, immixtum", vertaling: "vermengen", thema: 1, tekst: 5, zin: 292 },
  { grondvorm: "lumen", aanvullingen: "luminis (o.)", vertaling: "licht", repertorium: true, thema: 1, tekst: 5, zin: 292 },
  { grondvorm: "attollere", aanvullingen: "attollo, -, -", vertaling: "opheffen, oprichten", thema: 1, tekst: 5, zin: 293 },
  { grondvorm: "oculus", aanvullingen: "oculi (m.)", vertaling: "oog", repertorium: true, thema: 1, tekst: 5, zin: 293 },
  { grondvorm: "odium", aanvullingen: "odii (o.)", vertaling: "haat", repertorium: true, thema: 1, tekst: 5, zin: 293 },
  { grondvorm: "clementia", aanvullingen: "clementiae (v.)", vertaling: "zachtmoedigheid, mildheid", thema: 1, tekst: 5, zin: 293 },
  { grondvorm: "vincere", aanvullingen: "vinco, vici, victum", vertaling: "winnen, overwinnen", repertorium: true, thema: 1, tekst: 5, zin: 293 },
  { grondvorm: "inquit", aanvullingen: "defectief ww.", vertaling: "zegt hij, zei hij", repertorium: true, thema: 1, tekst: 5, zin: 294 },
  { grondvorm: "dementia", aanvullingen: "dementiae (v.)", vertaling: "waanzin", repertorium: true, thema: 1, tekst: 5, zin: 294 },
  { grondvorm: "sensus", aanvullingen: "sensus (m.)", vertaling: "gewaarwording, het voelen, gevoel", repertorium: true, thema: 1, tekst: 5, zin: 294 },
  { grondvorm: "ebrius", aanvullingen: "ebria, ebrium", vertaling: "dronken", repertorium: true, thema: 1, tekst: 5, zin: 295 },
  { grondvorm: "pervertere", aanvullingen: "perverto, perversi, pervertum", vertaling: "omdraaien, vervormen", thema: 1, tekst: 5, zin: 295 },
  { grondvorm: "notus", aanvullingen: "nota, notum", vertaling: "bekend", repertorium: true, thema: 1, tekst: 5, zin: 295 },
  { grondvorm: "meus", aanvullingen: "mea, meum", vertaling: "mijn", repertorium: true, thema: 1, tekst: 5, zin: 295 },
  { grondvorm: "res", aanvullingen: "rei (v.)", vertaling: "zaak, ding", repertorium: true, thema: 1, tekst: 5, zin: 296 },
  { grondvorm: "fama", aanvullingen: "famae (v.)", vertaling: "gerucht, faam, roem", repertorium: true, thema: 1, tekst: 5, zin: 296 },
  { grondvorm: "tantus", aanvullingen: "tanta, tantum", vertaling: "zo groot, zo veel", repertorium: true, thema: 1, tekst: 5, zin: 296 },
  { grondvorm: "perdere", aanvullingen: "perdo, perdidi, perditum", vertaling: "1. vernietigen; 2. verliezen", repertorium: true, thema: 1, tekst: 5, zin: 296 },
  { grondvorm: "fastus", aanvullingen: "fastus (m.)", vertaling: "hoogmoed", thema: 1, tekst: 5, zin: 296 },
  { grondvorm: "audere", aanvullingen: "audeo, ausus sum", vertaling: "durven", repertorium: true, thema: 1, tekst: 5, zin: 297 },
  { grondvorm: "conferre", aanvullingen: "confero, contuli, collatum", vertaling: "1. bijeenbrengen; 2. vergelijken", repertorium: true, thema: 1, tekst: 5, zin: 297 },
  { grondvorm: "signum", aanvullingen: "signi (o.)", vertaling: "teken, veldteken", repertorium: true, thema: 1, tekst: 5, zin: 297 },

  // ── Tekst 5: De uitdager (p.54) ──

  { grondvorm: "satis", aanvullingen: "bijw.", vertaling: "genoeg, voldoende", repertorium: true, thema: 1, tekst: 5, zin: 311 },
  { grondvorm: "ascendere", aanvullingen: "ascendo, ascendi, ascensum", vertaling: "stijgen", thema: 1, tekst: 5, zin: 311 },
  { grondvorm: "ascensus", aanvullingen: "ascensus (m.)", vertaling: "de opgang", thema: 1, tekst: 5, zin: 312 },
  { grondvorm: "regredi", aanvullingen: "regredior, regressus sum", vertaling: "terugkeren", repertorium: true, thema: 1, tekst: 5, zin: 312 },
  { grondvorm: "augmentum", aanvullingen: "augmenti (o.)", vertaling: "groei, toename", thema: 1, tekst: 5, zin: 313 },
  { grondvorm: "minuere", aanvullingen: "minuo, minui, minutum", vertaling: "verminderen, verkleinen", thema: 1, tekst: 5, zin: 313 },
  { grondvorm: "gravis", aanvullingen: "gravis, grave", vertaling: "1. zwaar; 2. erg, ernstig; 3. streng", repertorium: true, thema: 1, tekst: 5, zin: 313 },
  { grondvorm: "torquere", aanvullingen: "torqueo, torsi, tortum", vertaling: "1. draaien, al draaiend optrekken, slingeren; 2. folteren", repertorium: true, thema: 1, tekst: 5, zin: 313 },
  { grondvorm: "avarus", aanvullingen: "avari (m.)", vertaling: "vrek", thema: 1, tekst: 5, zin: 313 },
  { grondvorm: "amittere", aanvullingen: "amitto, amisi, amissum", vertaling: "1. wegzenden; 2. verliezen", repertorium: true, thema: 1, tekst: 5, zin: 314 },
  { grondvorm: "delectare", aanvullingen: "delecto, delectavi, delectatum", vertaling: "plezier doen, verblijden", repertorium: true, thema: 1, tekst: 5, zin: 314 },
  { grondvorm: "proinde", aanvullingen: "bijw.", vertaling: "dus, daarom", thema: 1, tekst: 5, zin: 315 },
  { grondvorm: "cursus", aanvullingen: "cursus (m.)", vertaling: "1. het lopen; 2. wedstrijd; 3. loopbaan, carrière", repertorium: true, thema: 1, tekst: 5, zin: 315 },
  { grondvorm: "frenum", aanvullingen: "freni (o.)", vertaling: "teugel, rem", thema: 1, tekst: 5, zin: 315 },
  { grondvorm: "moderare", aanvullingen: "modero, moderavi, moderatum", vertaling: "temperen", thema: 1, tekst: 5, zin: 315 },
  { grondvorm: "caducus", aanvullingen: "caduca, caducum", vertaling: "vergankelijk", thema: 1, tekst: 5, zin: 315 },
  { grondvorm: "bonum", aanvullingen: "boni (o.)", vertaling: "goederen", thema: 1, tekst: 5, zin: 316 },
  { grondvorm: "fortuna", aanvullingen: "fortunae (v.)", vertaling: "fortuin, lot, geluk", repertorium: true, thema: 1, tekst: 5, zin: 316 },

  // ══════════════════════════════════════════════════════════════
  // THEMA 2 – HISTORIOGRAFIE
  // Tekst 1: Gallië en z'n bewoners (p.24)
  // ══════════════════════════════════════════════════════════════

  { grondvorm: "Gallia", aanvullingen: "Galliae (v.)", vertaling: "Gallië", repertorium: true, thema: 2, tekst: 1, zin: 1 },
  { grondvorm: "omnis", aanvullingen: "omnis, omne", vertaling: "geheel, ieder, (mv.) allen", repertorium: true, thema: 2, tekst: 1, zin: 1 },
  { grondvorm: "dividere", aanvullingen: "divido, divisi, divisum", vertaling: "verdelen, scheiden", repertorium: true, thema: 2, tekst: 1, zin: 1 },
  { grondvorm: "in", aanvullingen: "(vz.) (+ acc.)", vertaling: "1. naar, tegen(over) (i.v.m. personen); 2. met het oog op", repertorium: true, thema: 2, tekst: 1, zin: 1 },
  { grondvorm: "tres", aanvullingen: "tres, tria", vertaling: "drie", repertorium: true, thema: 2, tekst: 1, zin: 1 },
  { grondvorm: "qui", aanvullingen: "quae, quod", vertaling: "die, dat", repertorium: true, thema: 2, tekst: 1, zin: 1 },
  { grondvorm: "unus", aanvullingen: "una, unum", vertaling: "één", repertorium: true, thema: 2, tekst: 1, zin: 1 },
  { grondvorm: "incolere", aanvullingen: "incolo, incolui, incolitum", vertaling: "bewonen", repertorium: true, thema: 2, tekst: 1, zin: 1 },
  { grondvorm: "Belgae", aanvullingen: "Belgarum (m. mv.)", vertaling: "de Belgen", repertorium: true, thema: 2, tekst: 1, zin: 1 },
  { grondvorm: "alius", aanvullingen: "alia, aliud", vertaling: "ander", repertorium: true, thema: 2, tekst: 1, zin: 1 },
  { grondvorm: "Aquitani", aanvullingen: "Aquitanorum (m. mv.)", vertaling: "de Aquitaniërs", thema: 2, tekst: 1, zin: 1 },
  { grondvorm: "tertius", aanvullingen: "tertia, tertium", vertaling: "derde", repertorium: true, thema: 2, tekst: 1, zin: 1 },
  { grondvorm: "lingua", aanvullingen: "linguae (v.)", vertaling: "1. tong; 2. taal", repertorium: true, thema: 2, tekst: 1, zin: 2 },
  { grondvorm: "Celtae", aanvullingen: "Celtarum (m. mv.)", vertaling: "de Kelten", repertorium: true, thema: 2, tekst: 1, zin: 2 },
  { grondvorm: "noster", aanvullingen: "nostra, nostrum", vertaling: "ons, onze", repertorium: true, thema: 2, tekst: 1, zin: 2 },
  { grondvorm: "Gallus", aanvullingen: "Galli (m.)", vertaling: "Galliër", repertorium: true, thema: 2, tekst: 1, zin: 2 },
  { grondvorm: "appellare", aanvullingen: "appello, appellavi, appellatum", vertaling: "roepen, noemen", repertorium: true, thema: 2, tekst: 1, zin: 2 },
  { grondvorm: "hic", aanvullingen: "haec, hoc (vnw.)", vertaling: "deze, dit", repertorium: true, thema: 2, tekst: 1, zin: 2 },
  { grondvorm: "institutum", aanvullingen: "instituti (o.)", vertaling: "gewoonten", thema: 2, tekst: 1, zin: 2 },
  { grondvorm: "lex", aanvullingen: "legis (v.)", vertaling: "wet", repertorium: true, thema: 2, tekst: 1, zin: 2 },
  { grondvorm: "inter", aanvullingen: "(vz.) (+ acc.)", vertaling: "1. tussen, te midden van; 2. onder", repertorium: true, thema: 2, tekst: 1, zin: 2 },
  { grondvorm: "differre", aanvullingen: "differo, distuli, dilatum", vertaling: "verspreiden, uitstellen, verschillen", repertorium: true, thema: 2, tekst: 1, zin: 2 },
  { grondvorm: "a(b)", aanvullingen: "(vz.) (+ abl.)", vertaling: "van, vanaf, sinds, door", repertorium: true, thema: 2, tekst: 1, zin: 3 },
  { grondvorm: "Garunna", aanvullingen: "Garunnae (v.)", vertaling: "De Garonne, rivier in Frankrijk", repertorium: true, thema: 2, tekst: 1, zin: 3 },
  { grondvorm: "flumen", aanvullingen: "fluminis (o.)", vertaling: "rivier", repertorium: true, thema: 2, tekst: 1, zin: 3 },
  { grondvorm: "Matrona", aanvullingen: "Matronae (v.)", vertaling: "De Marne, rivier in Frankrijk", repertorium: true, thema: 2, tekst: 1, zin: 3 },
  { grondvorm: "Sequana", aanvullingen: "Sequanae (v.)", vertaling: "De Seine, rivier in Frankrijk", repertorium: true, thema: 2, tekst: 1, zin: 3 },
  { grondvorm: "fortis", aanvullingen: "fortis, forte", vertaling: "sterk, moedig", repertorium: true, thema: 2, tekst: 1, zin: 4 },
  { grondvorm: "propterea", aanvullingen: "bijw.", vertaling: "vanwege", thema: 2, tekst: 1, zin: 4 },
  { grondvorm: "quod", aanvullingen: "+ ind.", vertaling: "dat, omdat", repertorium: true, thema: 2, tekst: 1, zin: 4 },
  { grondvorm: "cultus", aanvullingen: "cultus (m.)", vertaling: "1. verzorging; 2. bebouwing; 3. verering, eredienst; 4. beschaving", repertorium: true, thema: 2, tekst: 1, zin: 4 },
  { grondvorm: "humanitas", aanvullingen: "humanitatis (v.)", vertaling: "menselijkheid", thema: 2, tekst: 1, zin: 4 },
  { grondvorm: "Provincia", aanvullingen: "Provinciae (v.)", vertaling: "De Provence, streek in Zuid-Frankrijk", thema: 2, tekst: 1, zin: 4 },
  { grondvorm: "longus", aanvullingen: "longa, longum", vertaling: "lang, ver", repertorium: true, thema: 2, tekst: 1, zin: 5 },
  { grondvorm: "abesse", aanvullingen: "absum, afui, -", vertaling: "weg zijn, afwezig zijn, verwijderd zijn", repertorium: true, thema: 2, tekst: 1, zin: 5 },
  { grondvorm: "minime", aanvullingen: "bijw.", vertaling: "het minst", thema: 2, tekst: 1, zin: 5 },
  { grondvorm: "mercator", aanvullingen: "mercatoris (m.)", vertaling: "handelaar, (markt)kramer", thema: 2, tekst: 1, zin: 5 },
  { grondvorm: "saepe", aanvullingen: "bijw.", vertaling: "vaak, dikwijls", repertorium: true, thema: 2, tekst: 1, zin: 5 },
  { grondvorm: "commeare", aanvullingen: "commeo, commeavi, commeatum", vertaling: "komen", thema: 2, tekst: 1, zin: 5 },
  { grondvorm: "effeminare", aanvullingen: "effemino, effeminavi, effeminatum", vertaling: "verwijven, weekmaken", thema: 2, tekst: 1, zin: 5 },
  { grondvorm: "animus", aanvullingen: "animi (m.)", vertaling: "1. ziel, geest; 2. hart; 3. aard, karakter", repertorium: true, thema: 2, tekst: 1, zin: 6 },
  { grondvorm: "pertinere", aanvullingen: "pertineo, pertinui", vertaling: "behoren", thema: 2, tekst: 1, zin: 6 },
  { grondvorm: "importare", aanvullingen: "importo, importavi, importatum", vertaling: "aanvoeren", thema: 2, tekst: 1, zin: 6 },
  { grondvorm: "proximus", aanvullingen: "proxima, proximum", vertaling: "dichtst bij, naburig", repertorium: true, thema: 2, tekst: 1, zin: 6 },
  { grondvorm: "Germanus", aanvullingen: "Germani (m.)", vertaling: "Germaan", repertorium: true, thema: 2, tekst: 1, zin: 6 },
  { grondvorm: "trans", aanvullingen: "(vz.) (+ acc.)", vertaling: "over (…heen), aan de overzijde van", repertorium: true, thema: 2, tekst: 1, zin: 6 },
  { grondvorm: "Rhenus", aanvullingen: "Rheni (m.)", vertaling: "de Rijn", repertorium: true, thema: 2, tekst: 1, zin: 6 },
  { grondvorm: "cum", aanvullingen: "(vz.) (+ abl.)", vertaling: "met, samen met", repertorium: true, thema: 2, tekst: 1, zin: 6 },
  { grondvorm: "continenter", aanvullingen: "bijw.", vertaling: "voortdurend", thema: 2, tekst: 1, zin: 7 },
  { grondvorm: "bellum", aanvullingen: "belli (o.)", vertaling: "oorlog", repertorium: true, thema: 2, tekst: 1, zin: 7 },
  { grondvorm: "gerere", aanvullingen: "gero, gessi, gestum", vertaling: "dragen, voeren, maken, doen", repertorium: true, thema: 2, tekst: 1, zin: 7 },

  // ── Tekst 2: De druïden en hun onderwijs (p.50) ──

  { grondvorm: "druides", aanvullingen: "druidum (m.)", vertaling: "druïden", thema: 2, tekst: 2, zin: 1 },
  { grondvorm: "consuescere", aanvullingen: "consuesco, consuevi, consuetum", vertaling: "gewoon worden, wennen", repertorium: true, thema: 2, tekst: 2, zin: 1 },
  { grondvorm: "neque", aanvullingen: "vgw.", vertaling: "en (ook) niet, evenmin", repertorium: true, thema: 2, tekst: 2, zin: 1 },
  { grondvorm: "tributum", aanvullingen: "tributi (o.)", vertaling: "belasting", thema: 2, tekst: 2, zin: 1 },
  { grondvorm: "una", aanvullingen: "bijw.", vertaling: "samen", repertorium: true, thema: 2, tekst: 2, zin: 1 },
  { grondvorm: "reliquus", aanvullingen: "reliqua, reliquum", vertaling: "overig", repertorium: true, thema: 2, tekst: 2, zin: 1 },
  { grondvorm: "pendere", aanvullingen: "pendo, pependi", vertaling: "betalen", thema: 2, tekst: 2, zin: 1 },
  { grondvorm: "militia", aanvullingen: "militiae (v.)", vertaling: "krijgsdienst", thema: 2, tekst: 2, zin: 1 },
  { grondvorm: "vacatio", aanvullingen: "vacationis (v.)", vertaling: "vrijstelling", thema: 2, tekst: 2, zin: 1 },
  { grondvorm: "res", aanvullingen: "rei (v.)", vertaling: "zaak, ding, voorwerp, aangelegenheid", repertorium: true, thema: 2, tekst: 2, zin: 2 },
  { grondvorm: "habere", aanvullingen: "habeo, habui, habitum", vertaling: "hebben", repertorium: true, thema: 2, tekst: 2, zin: 2 },
  { grondvorm: "immunitas", aanvullingen: "immunitatis (v.)", vertaling: "vrijstelling", thema: 2, tekst: 2, zin: 2 },
  { grondvorm: "excitare", aanvullingen: "excito, excitavi, excitatum", vertaling: "aanmoedigen", repertorium: true, thema: 2, tekst: 2, zin: 2 },
  { grondvorm: "praemium", aanvullingen: "praemii (o.)", vertaling: "beloning", repertorium: true, thema: 2, tekst: 2, zin: 2 },
  { grondvorm: "suus", aanvullingen: "sua, suum", vertaling: "zijn, haar, hun (bezitt. vnw.)", repertorium: true, thema: 2, tekst: 2, zin: 2 },
  { grondvorm: "sponte", aanvullingen: "bijw.", vertaling: "uit eigen beweging", thema: 2, tekst: 2, zin: 2 },
  { grondvorm: "multus", aanvullingen: "multa, multum", vertaling: "veel", repertorium: true, thema: 2, tekst: 2, zin: 2 },
  { grondvorm: "disciplina", aanvullingen: "disciplinae (v.)", vertaling: "opleiding", thema: 2, tekst: 2, zin: 2 },
  { grondvorm: "convenire", aanvullingen: "convenio, conveni, conventum", vertaling: "samenkomen, overeenkomen", repertorium: true, thema: 2, tekst: 2, zin: 2 },
  { grondvorm: "parens", aanvullingen: "parentis (m./v.)", vertaling: "ouder (vader of moeder)", repertorium: true, thema: 2, tekst: 2, zin: 3 },
  { grondvorm: "propinquus", aanvullingen: "propinqua, propinquum (+dat.)", vertaling: "1. dichtbij gelegen, aangrenzend; 2. verwant", repertorium: true, thema: 2, tekst: 2, zin: 3 },
  { grondvorm: "mittere", aanvullingen: "mitto, misi, missum", vertaling: "1. zenden, sturen; 2. laten gaan", repertorium: true, thema: 2, tekst: 2, zin: 3 },
  { grondvorm: "magnus", aanvullingen: "magna, magnum", vertaling: "groot", repertorium: true, thema: 2, tekst: 2, zin: 3 },
  { grondvorm: "ibi", aanvullingen: "bijw.", vertaling: "daar", repertorium: true, thema: 2, tekst: 2, zin: 3 },
  { grondvorm: "numerus", aanvullingen: "numeri (m.)", vertaling: "aantal", repertorium: true, thema: 2, tekst: 2, zin: 3 },
  { grondvorm: "versus", aanvullingen: "versus (m.)", vertaling: "vers (van een gedicht)", repertorium: true, thema: 2, tekst: 2, zin: 3 },
  { grondvorm: "ediscere", aanvullingen: "edisco, edidici", vertaling: "uit het hoofd leren", thema: 2, tekst: 2, zin: 3 },
  { grondvorm: "dicere", aanvullingen: "dico, dixi, dictum", vertaling: "zeggen, spreken, noemen", repertorium: true, thema: 2, tekst: 2, zin: 3 },
  { grondvorm: "ita", aanvullingen: "bijw.", vertaling: "daarom", repertorium: true, thema: 2, tekst: 2, zin: 4 },
  { grondvorm: "annus", aanvullingen: "anni (m.)", vertaling: "jaar", repertorium: true, thema: 2, tekst: 2, zin: 4 },
  { grondvorm: "nonnullus", aanvullingen: "nonnulla, nonnullum", vertaling: "enkele, sommige, tamelijk veel", repertorium: true, thema: 2, tekst: 2, zin: 4 },
  { grondvorm: "vicenus", aanvullingen: "vicena, vicenum", vertaling: "twintig per keer", thema: 2, tekst: 2, zin: 4 },
  { grondvorm: "permanere", aanvullingen: "permaneo, permansi", vertaling: "blijven", thema: 2, tekst: 2, zin: 4 },
  { grondvorm: "fas", aanvullingen: "indecl.", vertaling: "goddelijke wet", thema: 2, tekst: 2, zin: 4 },
  { grondvorm: "existimare", aanvullingen: "existimo, existimavi, existimatum", vertaling: "menen, denken, oordelen", repertorium: true, thema: 2, tekst: 2, zin: 4 },
  { grondvorm: "littera", aanvullingen: "litterae (v.)", vertaling: "letter, (mv.) brief, letterkunde", repertorium: true, thema: 2, tekst: 2, zin: 4 },
  { grondvorm: "mandare", aanvullingen: "mando, mandavi, mandatum", vertaling: "toevertrouwen, bevelen", repertorium: true, thema: 2, tekst: 2, zin: 4 },
  { grondvorm: "publicus", aanvullingen: "publica, publicum", vertaling: "van de staat, openbaar", repertorium: true, thema: 2, tekst: 2, zin: 5 },
  { grondvorm: "privatus", aanvullingen: "privata, privatum", vertaling: "van een particulier, privaat, persoonlijk", repertorium: true, thema: 2, tekst: 2, zin: 5 },
  { grondvorm: "ratio", aanvullingen: "rationis (v.)", vertaling: "(be)rekening, verstand, redenering, reden", repertorium: true, thema: 2, tekst: 2, zin: 5 },
  { grondvorm: "Graecus", aanvullingen: "Graeca, Graecum", vertaling: "Grieks", repertorium: true, thema: 2, tekst: 2, zin: 5 },
  { grondvorm: "uti", aanvullingen: "utor, usus sum + abl.", vertaling: "gebruiken, omgaan met", repertorium: true, thema: 2, tekst: 2, zin: 5 },
  { grondvorm: "is", aanvullingen: "ea, id", vertaling: "die, dat (aanw. vnw.) / hij, zij, het (pers. vnw.)", repertorium: true, thema: 2, tekst: 2, zin: 5 },
  { grondvorm: "duo", aanvullingen: "duae, duo", vertaling: "twee", repertorium: true, thema: 2, tekst: 2, zin: 5 },
  { grondvorm: "de", aanvullingen: "(vz.) (+abl.)", vertaling: "over, vanaf, (weg) van", repertorium: true, thema: 2, tekst: 2, zin: 6 },
  { grondvorm: "causa", aanvullingen: "causae (v.)", vertaling: "1. oorzaak, reden; 2. rechtszaak, proces", repertorium: true, thema: 2, tekst: 2, zin: 6 },
  { grondvorm: "instituere", aanvullingen: "instituo, institui, institutum", vertaling: "1. oprichten, instellen; 2. onderrichten", repertorium: true, thema: 2, tekst: 2, zin: 6 },
  { grondvorm: "videri", aanvullingen: "videor, visum sum", vertaling: "schijnen, blijken, lijken", repertorium: true, thema: 2, tekst: 2, zin: 6 },
  { grondvorm: "vulgus", aanvullingen: "vulgi (o.)", vertaling: "het volk, het publiek", repertorium: true, thema: 2, tekst: 2, zin: 6 },
  { grondvorm: "efferre", aanvullingen: "effero, extuli, elatum", vertaling: "naar buiten brengen, wegbrengen", repertorium: true, thema: 2, tekst: 2, zin: 6 },
  { grondvorm: "velle", aanvullingen: "volo, volui, -", vertaling: "willen", repertorium: true, thema: 2, tekst: 2, zin: 6 },
  { grondvorm: "discere", aanvullingen: "disco, didici, -", vertaling: "leren, (onderwezen worden)", repertorium: true, thema: 2, tekst: 2, zin: 6 },
  { grondvorm: "confidere", aanvullingen: "confido, confisus sum (+ dat.)", vertaling: "vertrouwen op", repertorium: true, thema: 2, tekst: 2, zin: 7 },
  { grondvorm: "memoria", aanvullingen: "memoriae (v.)", vertaling: "geheugen, herinnering", repertorium: true, thema: 2, tekst: 2, zin: 7 },
  { grondvorm: "studere", aanvullingen: "studeo, studui, - +dat.", vertaling: "zich toeleggen op, streven naar, studeren", repertorium: true, thema: 2, tekst: 2, zin: 7 },
  { grondvorm: "plerusque", aanvullingen: "pleraque, plerumque", vertaling: "(meestal mv.) de meeste, zeer veel", repertorium: true, thema: 2, tekst: 2, zin: 7 },
  { grondvorm: "accidere", aanvullingen: "accido, accidi, -", vertaling: "vallen, voorvallen, gebeuren", repertorium: true, thema: 2, tekst: 2, zin: 7 },
  { grondvorm: "praesidium", aanvullingen: "praesidii (o.)", vertaling: "bescherming, hulp, wachtpost", repertorium: true, thema: 2, tekst: 2, zin: 7 },
  { grondvorm: "diligentia", aanvullingen: "diligentiae (v.)", vertaling: "ijver", thema: 2, tekst: 2, zin: 7 },
  { grondvorm: "perdiscere", aanvullingen: "perdisco, perdidici", vertaling: "grondig leren", thema: 2, tekst: 2, zin: 8 },
  { grondvorm: "ac", aanvullingen: "nevensch. vgw", vertaling: "en", repertorium: true, thema: 2, tekst: 2, zin: 8 },
  { grondvorm: "remittere", aanvullingen: "remitto, remisi, remissum", vertaling: "terugsturen, terugplaatsen", repertorium: true, thema: 2, tekst: 2, zin: 8 },

  // ── Tekst 3: Godsdienst van de Galliërs (p.56) ──

  { grondvorm: "natio", aanvullingen: "nationis (v.)", vertaling: "1. geboorte; 2. volk, stam, natie", repertorium: true, thema: 2, tekst: 3, zin: 1 },
  { grondvorm: "admodum", aanvullingen: "bijw.", vertaling: "zeer", thema: 2, tekst: 3, zin: 1 },
  { grondvorm: "deditus", aanvullingen: "dedita, deditum", vertaling: "toegewijd", thema: 2, tekst: 3, zin: 1 },
  { grondvorm: "religio", aanvullingen: "religionis (v.)", vertaling: "godsdienst", thema: 2, tekst: 3, zin: 1 },
  { grondvorm: "ob", aanvullingen: "(vz.) (+acc.)", vertaling: "wegens", repertorium: true, thema: 2, tekst: 3, zin: 1 },
  { grondvorm: "afficere", aanvullingen: "afficio, affeci, affectum", vertaling: "treffen, aandoen", thema: 2, tekst: 3, zin: 1 },
  { grondvorm: "morbus", aanvullingen: "morbi (m.)", vertaling: "ziekte", repertorium: true, thema: 2, tekst: 3, zin: 2 },
  { grondvorm: "proelium", aanvullingen: "proelii (o.)", vertaling: "gevecht, strijd", repertorium: true, thema: 2, tekst: 3, zin: 2 },
  { grondvorm: "periculum", aanvullingen: "periculi (o.)", vertaling: "gevaar", repertorium: true, thema: 2, tekst: 3, zin: 2 },
  { grondvorm: "versari", aanvullingen: "versor, versatus sum", vertaling: "zich bevinden", repertorium: true, thema: 2, tekst: 3, zin: 2 },
  { grondvorm: "aut", aanvullingen: "nevensch. vgw", vertaling: "of", repertorium: true, thema: 2, tekst: 3, zin: 2 },
  { grondvorm: "pro", aanvullingen: "(vz.) (+abl.)", vertaling: "in plaats van", repertorium: true, thema: 2, tekst: 3, zin: 2 },
  { grondvorm: "victima", aanvullingen: "victimae (v.)", vertaling: "offer(dier)", thema: 2, tekst: 3, zin: 2 },
  { grondvorm: "homo", aanvullingen: "hominis (m.)", vertaling: "mens", repertorium: true, thema: 2, tekst: 3, zin: 2 },
  { grondvorm: "immolare", aanvullingen: "immolo, immolavi, immolatum", vertaling: "offeren", thema: 2, tekst: 3, zin: 2 },
  { grondvorm: "se", aanvullingen: "refl. vnw.", vertaling: "zich", repertorium: true, thema: 2, tekst: 3, zin: 2 },
  { grondvorm: "vovere", aanvullingen: "voveo, vovi, votum", vertaling: "beloven", repertorium: true, thema: 2, tekst: 3, zin: 3 },
  { grondvorm: "administer", aanvullingen: "administri (m.)", vertaling: "helper", thema: 2, tekst: 3, zin: 3 },
  { grondvorm: "sacrificium", aanvullingen: "sacrificii (o.)", vertaling: "offer", thema: 2, tekst: 3, zin: 3 },
  { grondvorm: "vita", aanvullingen: "vitae (v.)", vertaling: "leven", repertorium: true, thema: 2, tekst: 3, zin: 3 },
  { grondvorm: "nisi", aanvullingen: "(vgw.) (+ind.,+conj.)", vertaling: "indien niet, als niet, tenzij", repertorium: true, thema: 2, tekst: 3, zin: 3 },
  { grondvorm: "reddere", aanvullingen: "reddo, reddidi, redditum", vertaling: "teruggeven, opleveren", repertorium: true, thema: 2, tekst: 3, zin: 3 },
  { grondvorm: "posse", aanvullingen: "possum, potui, -", vertaling: "kunnen", repertorium: true, thema: 2, tekst: 3, zin: 4 },
  { grondvorm: "deus", aanvullingen: "dei (m.)", vertaling: "god", repertorium: true, thema: 2, tekst: 3, zin: 4 },
  { grondvorm: "immortalis", aanvullingen: "immortalis, immortale", vertaling: "onsterfelijk", repertorium: true, thema: 2, tekst: 3, zin: 4 },
  { grondvorm: "numen", aanvullingen: "numinis (o.)", vertaling: "goddelijke wil, god", repertorium: true, thema: 2, tekst: 3, zin: 4 },
  { grondvorm: "placare", aanvullingen: "placo, placavi, placatum", vertaling: "verzoenen", thema: 2, tekst: 3, zin: 4 },
  { grondvorm: "arbitrari", aanvullingen: "arbitror, arbitratus sum", vertaling: "menen, oordelen", repertorium: true, thema: 2, tekst: 3, zin: 4 },
  { grondvorm: "idem", aanvullingen: "eadem, idem", vertaling: "dezelfde, hetzelfde", repertorium: true, thema: 2, tekst: 3, zin: 5 },
  { grondvorm: "genus", aanvullingen: "generis (o.)", vertaling: "1. afkomst; 2. familie; 3. soort", repertorium: true, thema: 2, tekst: 3, zin: 5 },
  { grondvorm: "immanis", aanvullingen: "immanis, immane", vertaling: "onmetelijk, reusachtig", repertorium: true, thema: 2, tekst: 3, zin: 5 },
  { grondvorm: "magnitudo", aanvullingen: "magnitudinis (v.)", vertaling: "grootte, omvang", repertorium: true, thema: 2, tekst: 3, zin: 5 },
  { grondvorm: "simulacrum", aanvullingen: "simulacri (o.)", vertaling: "beeld", thema: 2, tekst: 3, zin: 5 },
  { grondvorm: "contexere", aanvullingen: "contexo, contexui, contextum", vertaling: "vlechten, samenweven", thema: 2, tekst: 3, zin: 6 },
  { grondvorm: "vimen", aanvullingen: "viminis (o.)", vertaling: "twijg, takje", thema: 2, tekst: 3, zin: 6 },
  { grondvorm: "membrum", aanvullingen: "membri (o.)", vertaling: "(lichaams)deel, lid, ledematen", repertorium: true, thema: 2, tekst: 3, zin: 6 },
  { grondvorm: "vivus", aanvullingen: "viva, vivum", vertaling: "levend", repertorium: true, thema: 2, tekst: 3, zin: 6 },
  { grondvorm: "complere", aanvullingen: "compleo, complevi, completum", vertaling: "vullen, vervullen", repertorium: true, thema: 2, tekst: 3, zin: 6 },
  { grondvorm: "succendere", aanvullingen: "succendo, succensi, succensum", vertaling: "in brand steken", thema: 2, tekst: 3, zin: 6 },
  { grondvorm: "circumvenire", aanvullingen: "circumvenio, circumveni, circumventum", vertaling: "omsingelen", repertorium: true, thema: 2, tekst: 3, zin: 6 },
  { grondvorm: "flamma", aanvullingen: "flammae (v.)", vertaling: "vlam, vuur", repertorium: true, thema: 2, tekst: 3, zin: 6 },
  { grondvorm: "exanimare", aanvullingen: "exanimo, exanimavi, exanimatum", vertaling: "sterven", thema: 2, tekst: 3, zin: 7 },
  { grondvorm: "supplicium", aanvullingen: "supplicii (o.)", vertaling: "smeekbede, doodstraf, terechtstelling", repertorium: true, thema: 2, tekst: 3, zin: 7 },
  { grondvorm: "furtum", aanvullingen: "furti (o.)", vertaling: "diefstal", thema: 2, tekst: 3, zin: 7 },
  { grondvorm: "latricinium", aanvullingen: "latricinii (o.)", vertaling: "roof", thema: 2, tekst: 3, zin: 7 },
  { grondvorm: "aliquis", aanvullingen: "aliquis of aliqua, aliquid", vertaling: "(zelfst.) iemand, iets", repertorium: true, thema: 2, tekst: 3, zin: 7 },
  { grondvorm: "noxia", aanvullingen: "noxiae (v.)", vertaling: "misdaad, schuld", thema: 2, tekst: 3, zin: 7 },
  { grondvorm: "comprehendere", aanvullingen: "comprehendo, comprehendi, comprehensum", vertaling: "nemen, vastnemen, begrijpen", repertorium: true, thema: 2, tekst: 3, zin: 7 },
  { grondvorm: "gratus", aanvullingen: "grata, gratum", vertaling: "aangenaam, dankbaar", repertorium: true, thema: 2, tekst: 3, zin: 8 },
  { grondvorm: "sed", aanvullingen: "vgw.", vertaling: "maar", repertorium: true, thema: 2, tekst: 3, zin: 8 },
  { grondvorm: "cum", aanvullingen: "(vgw.) (+conj.)", vertaling: "toen, omdat, hoewel", repertorium: true, thema: 2, tekst: 3, zin: 8 },
  { grondvorm: "copia", aanvullingen: "copiae (v.)", vertaling: "voorraad, menigte", repertorium: true, thema: 2, tekst: 3, zin: 8 },
  { grondvorm: "deficere", aanvullingen: "deficio, defeci, defectum", vertaling: "ontbreken, opgeven, in de steek laten", repertorium: true, thema: 2, tekst: 3, zin: 8 },
  { grondvorm: "etiam", aanvullingen: "vgw.", vertaling: "ook, zelfs", repertorium: true, thema: 2, tekst: 3, zin: 8 },
  { grondvorm: "innocens", aanvullingen: "innocentis", vertaling: "onschuldig", thema: 2, tekst: 3, zin: 8 },
  { grondvorm: "descendere", aanvullingen: "descendo, descendi, descensum", vertaling: "afdalen", repertorium: true, thema: 2, tekst: 3, zin: 9 },

  // ── Tekst 4: Het complot (p.78) ──

  { grondvorm: "statim", aanvullingen: "bijw.", vertaling: "dadelijk", repertorium: true, thema: 2, tekst: 4, zin: 1 },
  { grondvorm: "confirmare", aanvullingen: "confirmo, confirmavi, confirmatum", vertaling: "1. versterken; 2. bevestigen; 3. bewijzen", repertorium: true, thema: 2, tekst: 4, zin: 1 },
  { grondvorm: "traditor", aanvullingen: "traditoris (m.)", vertaling: "verrader", thema: 2, tekst: 4, zin: 1 },
  { grondvorm: "requirere", aanvullingen: "requiro, requisivi, requisitum", vertaling: "zoeken, vragen, verlangen", thema: 2, tekst: 4, zin: 1 },
  { grondvorm: "quis", aanvullingen: "quis, quid (vragend vnw.)", vertaling: "wie? wat?", repertorium: true, thema: 2, tekst: 4, zin: 1 },
  { grondvorm: "facere", aanvullingen: "facio, feci, factum", vertaling: "doen, maken", repertorium: true, thema: 2, tekst: 4, zin: 1 },
  { grondvorm: "comes", aanvullingen: "comitis (m./v.)", vertaling: "begeleider, gezel; hier: graaf", repertorium: true, thema: 2, tekst: 4, zin: 1 },
  { grondvorm: "iste", aanvullingen: "ista, istud", vertaling: "die, dat", repertorium: true, thema: 2, tekst: 4, zin: 1 },
  { grondvorm: "laborare", aanvullingen: "laboro, laboravi, laboratum", vertaling: "werken, moeite doen, zich inspannen", repertorium: true, thema: 2, tekst: 4, zin: 1 },
  { grondvorm: "modus", aanvullingen: "modi (m.)", vertaling: "manier, wijze, maat", repertorium: true, thema: 2, tekst: 4, zin: 2 },
  { grondvorm: "destructio", aanvullingen: "destructionis (v.)", vertaling: "vernietiging, ondergang", thema: 2, tekst: 4, zin: 2 },
  { grondvorm: "servus", aanvullingen: "servi (m.)", vertaling: "slaaf, dienaar", repertorium: true, thema: 2, tekst: 4, zin: 2 },
  { grondvorm: "vindicare", aanvullingen: "vindico, vindicavi, vindicatum", vertaling: "opeisen, onderwerpen, wreken", thema: 2, tekst: 4, zin: 2 },
  { grondvorm: "festinare", aanvullingen: "festino, festinavi, festinatum", vertaling: "zich haasten", thema: 2, tekst: 4, zin: 2 },
  { grondvorm: "traditio", aanvullingen: "traditionis (v.)", vertaling: "overlevering, verraad", thema: 2, tekst: 4, zin: 2 },
  { grondvorm: "coniurare", aanvullingen: "coniuro, coniuravi, coniuratum", vertaling: "samenzweren", thema: 2, tekst: 4, zin: 3 },
  { grondvorm: "debere", aanvullingen: "debeo, debui, debitum", vertaling: "moeten, verschuldigd zijn", repertorium: true, thema: 2, tekst: 4, zin: 3 },
  { grondvorm: "amodo", aanvullingen: "bijw.", vertaling: "voortaan, van nu af", thema: 2, tekst: 4, zin: 3 },
  { grondvorm: "tam", aanvullingen: "bijw.", vertaling: "zo", repertorium: true, thema: 2, tekst: 4, zin: 3 },
  { grondvorm: "consilium", aanvullingen: "consilii (o.)", vertaling: "raad, plan, besluit", repertorium: true, thema: 2, tekst: 4, zin: 3 },
  { grondvorm: "quam", aanvullingen: "bijw.", vertaling: "dan (na comparatief); hoe", repertorium: true, thema: 2, tekst: 4, zin: 3 },
  { grondvorm: "peragere", aanvullingen: "perago, peregi, peractum", vertaling: "voltooien, uitvoeren", thema: 2, tekst: 4, zin: 3 },
  { grondvorm: "igitur", aanvullingen: "vgw.", vertaling: "dus, bijgevolg", repertorium: true, thema: 2, tekst: 4, zin: 4 },
  { grondvorm: "terrere", aanvullingen: "terreo, terrui, territum", vertaling: "verschrikken, bang maken", repertorium: true, thema: 2, tekst: 4, zin: 4 },
  { grondvorm: "puer", aanvullingen: "pueri (m.)", vertaling: "jongen", repertorium: true, thema: 2, tekst: 4, zin: 4 },
  { grondvorm: "lacrima", aanvullingen: "lacrimae (v.)", vertaling: "traan", repertorium: true, thema: 2, tekst: 4, zin: 4 },
  { grondvorm: "fundere", aanvullingen: "fundo, fudi, fusum", vertaling: "gieten, uitstorten", repertorium: true, thema: 2, tekst: 4, zin: 4 },
  { grondvorm: "ait", aanvullingen: "defectief werkwoord", vertaling: "zegt hij, zei hij", repertorium: true, thema: 2, tekst: 4, zin: 4 },
  { grondvorm: "dominus", aanvullingen: "domini (m.)", vertaling: "meester, heer", repertorium: true, thema: 2, tekst: 4, zin: 4 },
  { grondvorm: "tradere", aanvullingen: "trado, tradidi, traditum", vertaling: "uitleveren, overleveren", repertorium: true, thema: 2, tekst: 4, zin: 4 },
  { grondvorm: "patria", aanvullingen: "patriae (v.)", vertaling: "vaderland", repertorium: true, thema: 2, tekst: 4, zin: 5 },
  { grondvorm: "consul", aanvullingen: "consulis (m.)", vertaling: "consul (hoogste magistraat)", repertorium: true, thema: 2, tekst: 4, zin: 5 },
  { grondvorm: "imo", aanvullingen: "bijw.", vertaling: "integendeel, ja zelfs", thema: 2, tekst: 4, zin: 5 },
  { grondvorm: "revera", aanvullingen: "bijw.", vertaling: "werkelijk, in waarheid", thema: 2, tekst: 4, zin: 5 },
  { grondvorm: "desistere", aanvullingen: "desisto, destiti, destitum", vertaling: "ophouden, afzien van", thema: 2, tekst: 4, zin: 5 },
  { grondvorm: "vadere", aanvullingen: "vado, -, -", vertaling: "gaan", repertorium: true, thema: 2, tekst: 4, zin: 5 },
  { grondvorm: "aperte", aanvullingen: "bijw.", vertaling: "openlijk, zonder omwegen", thema: 2, tekst: 4, zin: 5 },
  { grondvorm: "vester", aanvullingen: "vestra, vestrum", vertaling: "jullie, uw", repertorium: true, thema: 2, tekst: 4, zin: 5 },
  { grondvorm: "universus", aanvullingen: "universa, universum", vertaling: "gezamenlijk, geheel", repertorium: true, thema: 2, tekst: 4, zin: 6 },
  { grondvorm: "eloqui", aanvullingen: "eloquor, elocutus sum", vertaling: "uitspreken, openlijk zeggen", thema: 2, tekst: 4, zin: 6 },
  { grondvorm: "super", aanvullingen: "(vz.) (+abl.)", vertaling: "boven, over, aangaande", repertorium: true, thema: 2, tekst: 4, zin: 6 },
  { grondvorm: "pactum", aanvullingen: "pacti (o.)", vertaling: "verdrag, afspraak, pact", thema: 2, tekst: 4, zin: 6 },
  { grondvorm: "vel", aanvullingen: "nevensch. vgw.", vertaling: "of", repertorium: true, thema: 2, tekst: 4, zin: 6 },
  { grondvorm: "auxilium", aanvullingen: "auxilii (o.)", vertaling: "hulp, hulpmiddel", repertorium: true, thema: 2, tekst: 4, zin: 6 },
  { grondvorm: "umquam", aanvullingen: "bijw.", vertaling: "ooit", repertorium: true, thema: 2, tekst: 4, zin: 6 },
  { grondvorm: "praestare", aanvullingen: "praesto, praestiti, praestitum", vertaling: "overtreffen, uitmunten, vervullen, verschaffen", repertorium: true, thema: 2, tekst: 4, zin: 6 },

  // ── Tekst 5: De aanslag (p.80) ──

  { grondvorm: "tunc", aanvullingen: "bijw.", vertaling: "op dat moment, toen, dan", repertorium: true, thema: 2, tekst: 5, zin: 1 },
  { grondvorm: "furibundus", aanvullingen: "furibunda, furibundum", vertaling: "razend, woedend", thema: 2, tekst: 5, zin: 1 },
  { grondvorm: "miles", aanvullingen: "militis (m.)", vertaling: "soldaat", repertorium: true, thema: 2, tekst: 5, zin: 1 },
  { grondvorm: "serviens", aanvullingen: "servientis (m.)", vertaling: "dienaar, dienende", thema: 2, tekst: 5, zin: 1 },
  { grondvorm: "simul", aanvullingen: "bijw.", vertaling: "tegelijk, samen", repertorium: true, thema: 2, tekst: 5, zin: 1 },
  { grondvorm: "accipere", aanvullingen: "accipio, accepi, acceptum", vertaling: "ontvangen, aannemen", repertorium: true, thema: 2, tekst: 5, zin: 1 },
  { grondvorm: "gladius", aanvullingen: "gladii (m.)", vertaling: "zwaard", repertorium: true, thema: 2, tekst: 5, zin: 1 },
  { grondvorm: "nudus", aanvullingen: "nuda, nudum", vertaling: "naakt, bloot, onbedekt", repertorium: true, thema: 2, tekst: 5, zin: 1 },

];

// Hulpfuncties
function getByThema(thema) {
  return woordenlijst_4ds.filter(w => w.thema === thema);
}

function getByTekst(thema, tekst) {
  return woordenlijst_4ds.filter(w => w.thema === thema && w.tekst === tekst);
}

function getRepertorium() {
  return woordenlijst_4ds.filter(w => w.repertorium === true);
}
