// Woordenlijst 3DS LAT – S.O. Groenhove Waregem
// Gebaseerd op de gedrukte woordenlijst 3DS LAT (J.E.)
// Structuur: { grondvorm, aanvullingen, vertaling, repertorium?, thema, tekst, zin }
// repertorium: true = woord gemarkeerd met □ (vet, kernwoordenschat)
// Thema 1: ANIMO SUBDOLO | Thema 2: VITA AN SPECIES?

const woordenlijst_3ds = [

  // ══════════════════════════════════════════════════════════════
  // THEMA 1 – ANIMO SUBDOLO
  // Tekst 1: De vulpe et lupo (p.12)
  // ══════════════════════════════════════════════════════════════

  { grondvorm: "vulpes", aanvullingen: "vulpis (v.)", vertaling: "vos", thema: 1, tekst: 1, zin: 1 },
  { grondvorm: "casu", aanvullingen: "bijw.", vertaling: "per ongeluk", thema: 1, tekst: 1, zin: 1 },
  { grondvorm: "cadere", aanvullingen: "cado, cecidi, -", vertaling: "vallen, voorvallen", repertorium: true, thema: 1, tekst: 1, zin: 1 },
  { grondvorm: "per", aanvullingen: "vz. + acc.", vertaling: "1. door(...heen); 2. door toedoen van; 3. gedurende", repertorium: true, thema: 1, tekst: 1, zin: 1 },
  { grondvorm: "situla", aanvullingen: "situlae (v.)", vertaling: "emmer", thema: 1, tekst: 1, zin: 1 },
  { grondvorm: "puteus", aanvullingen: "putei (m.)", vertaling: "(water)put", thema: 1, tekst: 1, zin: 1 },
  { grondvorm: "lupus", aanvullingen: "lupi (m.)", vertaling: "wolf", thema: 1, tekst: 1, zin: 1 },
  { grondvorm: "venire", aanvullingen: "venio, veni, ventum", vertaling: "komen", repertorium: true, thema: 1, tekst: 1, zin: 1 },
  { grondvorm: "quaerere", aanvullingen: "quaero, quaesivi, quaesitum", vertaling: "1. zoeken; 2. vragen; 3. nastreven", repertorium: true, thema: 1, tekst: 1, zin: 1 },
  { grondvorm: "ibi", aanvullingen: "bijw.", vertaling: "daar", repertorium: true, thema: 1, tekst: 1, zin: 1 },
  { grondvorm: "vulpecula", aanvullingen: "vulpeculae (v.)", vertaling: "vosje", thema: 1, tekst: 1, zin: 1 },
  { grondvorm: "ait", aanvullingen: "(defectief ww.)", vertaling: "zegt hij, zei hij", repertorium: true, thema: 1, tekst: 1, zin: 2 },
  { grondvorm: "compater", aanvullingen: "compatris (m.)", vertaling: "vriend", thema: 1, tekst: 1, zin: 2 },
  { grondvorm: "hic", aanvullingen: "bijw.", vertaling: "hier", repertorium: true, thema: 1, tekst: 1, zin: 2 },
  { grondvorm: "piscis", aanvullingen: "piscis (m.)", vertaling: "vis", thema: 1, tekst: 1, zin: 2 },
  { grondvorm: "utinam", aanvullingen: "bijw.", vertaling: "hopelijk", thema: 1, tekst: 1, zin: 2 },
  { grondvorm: "pars", aanvullingen: "partis (v.)", vertaling: "deel, zijde", repertorium: true, thema: 1, tekst: 1, zin: 2 },
  { grondvorm: "quomodo", aanvullingen: "bijw.", vertaling: "hoe?", repertorium: true, thema: 1, tekst: 1, zin: 3 },
  { grondvorm: "descendere", aanvullingen: "descendo, descendi, descensum", vertaling: "afdalen", repertorium: true, thema: 1, tekst: 1, zin: 3 },
  { grondvorm: "superesse", aanvullingen: "supersum, superfui, -", vertaling: "boven zijn", repertorium: true, thema: 1, tekst: 1, zin: 3 },
  { grondvorm: "ponere", aanvullingen: "pono, posui, positum", vertaling: "plaatsen, leggen", repertorium: true, thema: 1, tekst: 1, zin: 3 },
  { grondvorm: "intus", aanvullingen: "bijw.", vertaling: "binnen(in)", thema: 1, tekst: 1, zin: 3 },
  { grondvorm: "deorsum", aanvullingen: "bijw.", vertaling: "beneden", thema: 1, tekst: 1, zin: 4 },
  { grondvorm: "quando", aanvullingen: "+ ind.", vertaling: "wanneer, toen, omdat", repertorium: true, thema: 1, tekst: 1, zin: 4 },
  { grondvorm: "alius", aanvullingen: "alia, aliud", vertaling: "ander", repertorium: true, thema: 1, tekst: 1, zin: 4 },
  { grondvorm: "ascendere", aanvullingen: "ascendo, ascendi, ascensum", vertaling: "opstijgen", thema: 1, tekst: 1, zin: 4 },
  { grondvorm: "supra", aanvullingen: "bijw.", vertaling: "1. boven; 2. eerder, vroeger", repertorium: true, thema: 1, tekst: 1, zin: 5 },
  { grondvorm: "obviare", aanvullingen: "obvio, obviavi, obviatum + dat.", vertaling: "ontmoeten", thema: 1, tekst: 1, zin: 5 },
  { grondvorm: "quo", aanvullingen: "bijw.", vertaling: "waarheen?", repertorium: true, thema: 1, tekst: 1, zin: 6 },
  { grondvorm: "vadere", aanvullingen: "vado, -, -", vertaling: "gaan", repertorium: true, thema: 1, tekst: 1, zin: 6 },
  { grondvorm: "satis", aanvullingen: "bijw.", vertaling: "genoeg, voldoende", repertorium: true, thema: 1, tekst: 1, zin: 6 },
  { grondvorm: "comedere", aanvullingen: "comedo, comedi, comessum", vertaling: "opeten, verteren", thema: 1, tekst: 1, zin: 6 },
  { grondvorm: "invenire", aanvullingen: "invenio, inveni, inventum", vertaling: "vinden, uitvinden, ontdekken", repertorium: true, thema: 1, tekst: 1, zin: 7 },
  { grondvorm: "mirabilis", aanvullingen: "mirabilis, mirabile", vertaling: "verwonderlijk, verbazingwekkend", thema: 1, tekst: 1, zin: 7 },
  { grondvorm: "miser", aanvullingen: "misera, miserum", vertaling: "ellendig, ongelukkig", repertorium: true, thema: 1, tekst: 1, zin: 7 },
  { grondvorm: "nec", aanvullingen: "nevensch. vgw.", vertaling: "en (ook)niet", repertorium: true, thema: 1, tekst: 1, zin: 7 },
  { grondvorm: "aliquis", aanvullingen: "aliquis of aliqua, aliquid", vertaling: "iemand, iets (zelfstandig)", repertorium: true, thema: 1, tekst: 1, zin: 7 },
  { grondvorm: "nisi", aanvullingen: "vgw. (+ind.,+conj.)", vertaling: "indien niet, als niet, tenzij", repertorium: true, thema: 1, tekst: 1, zin: 7 },
  { grondvorm: "mane", aanvullingen: "bijw.", vertaling: "'s morgens", thema: 1, tekst: 1, zin: 7 },
  { grondvorm: "rusticus", aanvullingen: "rustici (m.)", vertaling: "boer", thema: 1, tekst: 1, zin: 7 },
  { grondvorm: "extrahere", aanvullingen: "extraho, extraxi, extractum", vertaling: "uittrekken", thema: 1, tekst: 1, zin: 8 },
  { grondvorm: "usque ad", aanvullingen: "-", vertaling: "tot aan", thema: 1, tekst: 1, zin: 8 },
  { grondvorm: "mors", aanvullingen: "mortis (v.)", vertaling: "dood", repertorium: true, thema: 1, tekst: 1, zin: 8 },
  { grondvorm: "verberare", aanvullingen: "verbero, verberavi, verberatum", vertaling: "slaan", thema: 1, tekst: 1, zin: 8 },

  // ── Tekst 2: Mercurius, de dief (p.38) ──

  { grondvorm: "ille", aanvullingen: "illa, illud", vertaling: "die, dat", repertorium: true, thema: 1, tekst: 2, zin: 680 },
  { grondvorm: "tempus", aanvullingen: "temporis (o.)", vertaling: "tijd(stip)", repertorium: true, thema: 1, tekst: 2, zin: 680 },
  { grondvorm: "qui", aanvullingen: "quae, quod", vertaling: "die, dat (betrekkelijk voornaamwoord)", repertorium: true, thema: 1, tekst: 2, zin: 680 },
  { grondvorm: "pastorius", aanvullingen: "pastoria, pastorium", vertaling: "van een herder", thema: 1, tekst: 2, zin: 680 },
  { grondvorm: "pellis", aanvullingen: "pellis (v.)", vertaling: "pels, vel, huid", thema: 1, tekst: 2, zin: 680 },
  { grondvorm: "tegere", aanvullingen: "tego, texi, tectum", vertaling: "bedekken", repertorium: true, thema: 1, tekst: 2, zin: 681 },
  { grondvorm: "onus", aanvullingen: "oneris (o.)", vertaling: "last", thema: 1, tekst: 2, zin: 681 },
  { grondvorm: "baculum", aanvullingen: "baculi (o.)", vertaling: "herdersstaf", thema: 1, tekst: 2, zin: 681 },
  { grondvorm: "silvestris", aanvullingen: "silvestris, silvestre", vertaling: "bosrijk", thema: 1, tekst: 2, zin: 681 },
  { grondvorm: "sinister", aanvullingen: "sinistra, sinistrum", vertaling: "links, linker-, ongunstig", repertorium: true, thema: 1, tekst: 2, zin: 681 },
  { grondvorm: "alter", aanvullingen: "altera, alterum", vertaling: "de andere (van twee)", repertorium: true, thema: 1, tekst: 2, zin: 682 },
  { grondvorm: "dispar", aanvullingen: "dispar, dispar, gen. disparis", vertaling: "ongelijk", thema: 1, tekst: 2, zin: 682 },
  { grondvorm: "septeni", aanvullingen: "septenae, septena", vertaling: "elk zeven", thema: 1, tekst: 2, zin: 682 },
  { grondvorm: "fistula", aanvullingen: "fistulae (v.)", vertaling: "pijp, buis", thema: 1, tekst: 2, zin: 682 },
  { grondvorm: "canna", aanvullingen: "cannae (v.)", vertaling: "riet", thema: 1, tekst: 2, zin: 682 },
  { grondvorm: "dum", aanvullingen: "(vgw.) + ind.", vertaling: "terwijl, zolang, totdat", repertorium: true, thema: 1, tekst: 2, zin: 683 },
  { grondvorm: "amor", aanvullingen: "amoris (m.)", vertaling: "liefde", repertorium: true, thema: 1, tekst: 2, zin: 683 },
  { grondvorm: "cura", aanvullingen: "curae (v.)", vertaling: "1. zorg, verzorging; 2. bezorgdheid", repertorium: true, thema: 1, tekst: 2, zin: 683 },
  { grondvorm: "mulcere", aanvullingen: "mulceo, mulsi, mulsum", vertaling: "aaien, strelen", thema: 1, tekst: 2, zin: 683 },
  { grondvorm: "incustoditus", aanvullingen: "incustodita, incustoditum", vertaling: "onbewaakt", thema: 1, tekst: 2, zin: 684 },
  { grondvorm: "Pylius", aanvullingen: "Pylia, Pylium", vertaling: "Pylisch", thema: 1, tekst: 2, zin: 684 },
  { grondvorm: "memorare", aanvullingen: "memoro, memoravi, memoratum", vertaling: "zich herinneren", repertorium: true, thema: 1, tekst: 2, zin: 684 },
  { grondvorm: "ager", aanvullingen: "agri (m.)", vertaling: "akker, veld", repertorium: true, thema: 1, tekst: 2, zin: 684 },
  { grondvorm: "procedere", aanvullingen: "procedo, processi, processum", vertaling: "vooruitgaan, naar voren treden", repertorium: true, thema: 1, tekst: 2, zin: 685 },
  { grondvorm: "bos", aanvullingen: "bovis (m/v.)", vertaling: "rund", repertorium: true, thema: 1, tekst: 2, zin: 685 },
  { grondvorm: "hic", aanvullingen: "haec, hoc", vertaling: "deze, dit", repertorium: true, thema: 1, tekst: 2, zin: 685 },
  { grondvorm: "Atlantides", aanvullingen: "Atlantidis (m.)", vertaling: "kleinzoon van Atlas, dus Mercurius", thema: 1, tekst: 2, zin: 685 },
  { grondvorm: "Maia", aanvullingen: "Maiae (v.)", vertaling: "moeder van Mercurius, Maia", thema: 1, tekst: 2, zin: 685 },
  { grondvorm: "nasci", aanvullingen: "nascor, natus sum", vertaling: "geboren worden, afstammen van", repertorium: true, thema: 1, tekst: 2, zin: 686 },
  { grondvorm: "natus", aanvullingen: "nati (m.)", vertaling: "zoon", repertorium: true, thema: 1, tekst: 2, zin: 686 },
  { grondvorm: "ars", aanvullingen: "artis (v.)", vertaling: "1. kunst; 2. vaardigheid", repertorium: true, thema: 1, tekst: 2, zin: 686 },
  { grondvorm: "silva", aanvullingen: "silvae (v.)", vertaling: "bos, woud", repertorium: true, thema: 1, tekst: 2, zin: 686 },
  { grondvorm: "occultare", aanvullingen: "occulto, occultavi, occultatum", vertaling: "verbergen", thema: 1, tekst: 2, zin: 686 },
  { grondvorm: "abigere", aanvullingen: "abigo, abegi, abactum", vertaling: "verdrijven, verjagen", thema: 1, tekst: 2, zin: 686 },
  { grondvorm: "sentire", aanvullingen: "sentio, sensi, sensum", vertaling: "1. voelen, merken; 2. denken", repertorium: true, thema: 1, tekst: 2, zin: 687 },
  { grondvorm: "furtum", aanvullingen: "furti (o.)", vertaling: "diefstal", thema: 1, tekst: 2, zin: 687 },
  { grondvorm: "nemo", aanvullingen: "neminis (o.)", vertaling: "niemand", repertorium: true, thema: 1, tekst: 2, zin: 687 },
  { grondvorm: "notus", aanvullingen: "nota, notum", vertaling: "bekend", repertorium: true, thema: 1, tekst: 2, zin: 687 },
  { grondvorm: "rus", aanvullingen: "ruris (o.)", vertaling: "platteland", thema: 1, tekst: 2, zin: 688 },
  { grondvorm: "senex", aanvullingen: "senis (m.)", vertaling: "oude man", repertorium: true, thema: 1, tekst: 2, zin: 688 },
  { grondvorm: "Battus", aanvullingen: "Batti (m.)", vertaling: "Battus, de herder in dit verhaal", thema: 1, tekst: 2, zin: 688 },
  { grondvorm: "vicinia", aanvullingen: "viciniae (v.)", vertaling: "de buurt", thema: 1, tekst: 2, zin: 688 },
  { grondvorm: "totus", aanvullingen: "tota, totum", vertaling: "geheel", repertorium: true, thema: 1, tekst: 2, zin: 688 },
  { grondvorm: "vocare", aanvullingen: "voco, vocavi, vocatum", vertaling: "1. roepen; 2. noemen", repertorium: true, thema: 1, tekst: 2, zin: 688 },

  // ── Tekst 2: Mercurius, de dief (p.44) ──

  { grondvorm: "dives", aanvullingen: "dives, dives, (gen.) divitis", vertaling: "rijk", repertorium: true, thema: 1, tekst: 2, zin: 689 },
  { grondvorm: "saltus", aanvullingen: "saltus (m.)", vertaling: "kloof, ravijn", thema: 1, tekst: 2, zin: 689 },
  { grondvorm: "herbosus", aanvullingen: "herbosa, herbosum", vertaling: "gras- of kruidenrijk", thema: 1, tekst: 2, zin: 689 },
  { grondvorm: "pascuus", aanvullingen: "pascua, pascuum", vertaling: "landelijk", thema: 1, tekst: 2, zin: 689 },
  { grondvorm: "Neleus", aanvullingen: "Nelei (m.)", vertaling: "Neleus", thema: 1, tekst: 2, zin: 689 },
  { grondvorm: "nobilis", aanvullingen: "nobilis, nobile", vertaling: "aanzienlijk, adellijk", repertorium: true, thema: 1, tekst: 2, zin: 690 },
  { grondvorm: "grex", aanvullingen: "gregis (m.)", vertaling: "kudde, troep", repertorium: true, thema: 1, tekst: 2, zin: 690 },
  { grondvorm: "custos", aanvullingen: "custodis (m.)", vertaling: "bewaker", repertorium: true, thema: 1, tekst: 2, zin: 690 },
  { grondvorm: "servare", aanvullingen: "servo, servavi, servatum", vertaling: "1. bewaren; 2. bewaken", repertorium: true, thema: 1, tekst: 2, zin: 690 },
  { grondvorm: "equa", aanvullingen: "equae (v.)", vertaling: "merrie", thema: 1, tekst: 2, zin: 690 },
  { grondvorm: "tenere", aanvullingen: "teneo, tenui, tentum", vertaling: "houden, vasthouden", repertorium: true, thema: 1, tekst: 2, zin: 691 },
  { grondvorm: "blandus", aanvullingen: "blanda, blandum", vertaling: "vleiend, hoffelijk", thema: 1, tekst: 2, zin: 691 },
  { grondvorm: "seducere", aanvullingen: "seduco, seduxi, seductum", vertaling: "1. apart nemen; 2. verleiden", thema: 1, tekst: 2, zin: 691 },
  { grondvorm: "quisque", aanvullingen: "quisquis, quicquid of quodquid", vertaling: "wie ook", thema: 1, tekst: 2, zin: 692 },
  { grondvorm: "hospes", aanvullingen: "hospitis (m.)", vertaling: "1. gast, gastheer; 2. vreemdeling", repertorium: true, thema: 1, tekst: 2, zin: 692 },
  { grondvorm: "forte", aanvullingen: "bijw.", vertaling: "toevallig", repertorium: true, thema: 1, tekst: 2, zin: 692 },
  { grondvorm: "armentum", aanvullingen: "armenti (o.)", vertaling: "kudde", thema: 1, tekst: 2, zin: 692 },
  { grondvorm: "requirere", aanvullingen: "requiro, requisivi, requisitum", vertaling: "zoeken, navragen", thema: 1, tekst: 2, zin: 692 },
  { grondvorm: "negare", aanvullingen: "nego, negavi, negatum", vertaling: "ontkennen, neen zeggen", repertorium: true, thema: 1, tekst: 2, zin: 693 },
  { grondvorm: "neu", aanvullingen: "nevensch. vgw.", vertaling: "en niet, of niet", thema: 1, tekst: 2, zin: 693 },
  { grondvorm: "gratia", aanvullingen: "gratiae (v.)", vertaling: "1. bevalligheid, charme; 2. gunst, dank; 3. aanzien", repertorium: true, thema: 1, tekst: 2, zin: 693 },
  { grondvorm: "factum", aanvullingen: "facti (o.)", vertaling: "daad, feit, voorval", repertorium: true, thema: 1, tekst: 2, zin: 693 },
  { grondvorm: "nullus", aanvullingen: "nulla, nullum", vertaling: "geen (enkele)", repertorium: true, thema: 1, tekst: 2, zin: 694 },
  { grondvorm: "rependere", aanvullingen: "rependo, rependi, repensum", vertaling: "belonen", thema: 1, tekst: 2, zin: 694 },
  { grondvorm: "nitidus", aanvullingen: "nitida, nitidum", vertaling: "glanzend, glimmend", thema: 1, tekst: 2, zin: 694 },
  { grondvorm: "capere", aanvullingen: "capio, cepi, captum", vertaling: "nemen, grijpen", repertorium: true, thema: 1, tekst: 2, zin: 694 },
  { grondvorm: "praemium", aanvullingen: "praemii (o.)", vertaling: "beloning", repertorium: true, thema: 1, tekst: 2, zin: 694 },
  { grondvorm: "vacca", aanvullingen: "vaccae (v.)", vertaling: "koe", thema: 1, tekst: 2, zin: 694 },
  { grondvorm: "dare", aanvullingen: "do, dedi, datum", vertaling: "geven", repertorium: true, thema: 1, tekst: 2, zin: 695 },
  { grondvorm: "accipere", aanvullingen: "accipio, accepi, acceptum", vertaling: "ontvangen, aannemen", repertorium: true, thema: 1, tekst: 2, zin: 695 },
  { grondvorm: "vox", aanvullingen: "vocis (v.)", vertaling: "1. stem; 2. geluid; 3. woord", repertorium: true, thema: 1, tekst: 2, zin: 695 },
  { grondvorm: "reddere", aanvullingen: "reddo, reddidi, redditum", vertaling: "1. teruggeven; 2. opleveren", repertorium: true, thema: 1, tekst: 2, zin: 695 },
  { grondvorm: "tutus", aanvullingen: "tuta, tutum", vertaling: "veilig, voorzichtig", repertorium: true, thema: 1, tekst: 2, zin: 696 },
  { grondvorm: "ire", aanvullingen: "eo, ii, itum", vertaling: "gaan", repertorium: true, thema: 1, tekst: 2, zin: 696 },
  { grondvorm: "lapis", aanvullingen: "lapidis (m.)", vertaling: "steen", repertorium: true, thema: 1, tekst: 2, zin: 696 },
  { grondvorm: "iste", aanvullingen: "ista, istud", vertaling: "die, dat (negatief)", repertorium: true, thema: 1, tekst: 2, zin: 696 },
  { grondvorm: "prior", aanvullingen: "prior, prius, gen. prioris", vertaling: "vroeger, eerder", repertorium: true, thema: 1, tekst: 2, zin: 696 },
  { grondvorm: "loqui", aanvullingen: "loquor, locutus sum", vertaling: "spreken, zeggen", repertorium: true, thema: 1, tekst: 2, zin: 696 },
  { grondvorm: "ostendere", aanvullingen: "ostendo, ostendi, ostentum", vertaling: "tonen, aantonen", repertorium: true, thema: 1, tekst: 2, zin: 697 },
  { grondvorm: "simulare", aanvullingen: "simulo, simulavi, simulatum", vertaling: "nabootsen, veinzen, doen alsof", repertorium: true, thema: 1, tekst: 2, zin: 697 },
  { grondvorm: "Iuppiter", aanvullingen: "Iovis (m.)", vertaling: "Jupiter of Zeus (de oppergod)", repertorium: true, thema: 1, tekst: 2, zin: 697 },
  { grondvorm: "abire", aanvullingen: "abeo, abii, abitum", vertaling: "weggaan", repertorium: true, thema: 1, tekst: 2, zin: 697 },

  // ── Tekst 3: Een hobbit en een draak (p.56) ──

  { grondvorm: "tum", aanvullingen: "bijw.", vertaling: "1. op dat moment, toen, dan; 2. vervolgens", repertorium: true, thema: 1, tekst: 3, zin: 1 },
  { grondvorm: "Smaug", aanvullingen: "Smaugis (m.)", vertaling: "Smaug, de draak in dit verhaal", thema: 1, tekst: 3, zin: 1 },
  { grondvorm: "ita", aanvullingen: "bijw.", vertaling: "zo", repertorium: true, thema: 1, tekst: 3, zin: 1 },
  { grondvorm: "fur", aanvullingen: "furis (m.)", vertaling: "dief", thema: 1, tekst: 3, zin: 1 },
  { grondvorm: "olfacere", aanvullingen: "olfacio, olfeci, olfactum", vertaling: "ruiken", thema: 1, tekst: 3, zin: 1 },
  { grondvorm: "aer", aanvullingen: "aëris", vertaling: "lucht", repertorium: true, thema: 1, tekst: 3, zin: 1 },
  { grondvorm: "spiritus", aanvullingen: "spiritus (m.)", vertaling: "adem, ziel, geest", repertorium: true, thema: 1, tekst: 3, zin: 1 },
  { grondvorm: "tuus", aanvullingen: "tua, tuum", vertaling: "jouw", repertorium: true, thema: 1, tekst: 3, zin: 1 },
  { grondvorm: "huc", aanvullingen: "bijw.", vertaling: "hierheen, naar hier", repertorium: true, thema: 1, tekst: 3, zin: 1 },
  { grondvorm: "ipse", aanvullingen: "ipsa, ipsum", vertaling: "zelf", repertorium: true, thema: 1, tekst: 3, zin: 1 },
  { grondvorm: "iterum", aanvullingen: "bijw.", vertaling: "opnieuw, nog eens", repertorium: true, thema: 1, tekst: 3, zin: 2 },
  { grondvorm: "donum", aanvullingen: "doni (o.)", vertaling: "geschenk", repertorium: true, thema: 1, tekst: 3, zin: 2 },
  { grondvorm: "carpere", aanvullingen: "carpo, carpsi, carptum", vertaling: "plukken, genieten van", repertorium: true, thema: 1, tekst: 3, zin: 2 },
  { grondvorm: "nam", aanvullingen: "nevensch. vgw.", vertaling: "want", repertorium: true, thema: 1, tekst: 3, zin: 2 },
  { grondvorm: "tam", aanvullingen: "bijw.", vertaling: "zo", repertorium: true, thema: 1, tekst: 3, zin: 3 },
  { grondvorm: "indoctus", aanvullingen: "indocta, indoctum", vertaling: "ongeleerd, onbekend", thema: 1, tekst: 3, zin: 3 },
  { grondvorm: "doctrina dracorum", aanvullingen: "doctrinae dracorum", vertaling: "drakenkunde", thema: 1, tekst: 3, zin: 3 },
  { grondvorm: "sperare", aanvullingen: "spero, speravi, speratum", vertaling: "hopen", repertorium: true, thema: 1, tekst: 3, zin: 3 },
  { grondvorm: "propior", aanvullingen: "propior, propius (+ dat.)", vertaling: "dichter, dichterbij", repertorium: true, thema: 1, tekst: 3, zin: 3 },
  { grondvorm: "falsus", aanvullingen: "falsa, falsum", vertaling: "vals", repertorium: true, thema: 1, tekst: 3, zin: 4 },
  { grondvorm: "tremendus", aanvullingen: "tremenda, tremendum", vertaling: "angstaanjagend", thema: 1, tekst: 3, zin: 4 },
  { grondvorm: "respondere", aanvullingen: "respondeo, respondi, responsum", vertaling: "antwoorden, beantwoorden", repertorium: true, thema: 1, tekst: 3, zin: 4 },
  { grondvorm: "gen + causa", aanvullingen: "", vertaling: "omwille van", repertorium: true, thema: 1, tekst: 3, zin: 4 },
  { grondvorm: "modo", aanvullingen: "bijw.", vertaling: "slechts, (zo) pas, onlangs", repertorium: true, thema: 1, tekst: 3, zin: 5 },
  { grondvorm: "cupere", aanvullingen: "cupio, cupivi, cupitum", vertaling: "verlangen", repertorium: true, thema: 1, tekst: 3, zin: 5 },
  { grondvorm: "aspicere", aanvullingen: "aspicio, aspexi, aspectum", vertaling: "kijken naar, aankijken", repertorium: true, thema: 1, tekst: 3, zin: 5 },
  { grondvorm: "cognoscere", aanvullingen: "cognosco, cognovi, cognotum", vertaling: "1. leren kennen; 2. herkennen; 3. vernemen", repertorium: true, thema: 1, tekst: 3, zin: 5 },
  { grondvorm: "num", aanvullingen: "vraagpartikel", vertaling: "toch niet?", repertorium: true, thema: 1, tekst: 3, zin: 5 },
  { grondvorm: "verus", aanvullingen: "vera, verum", vertaling: "echt, waar", repertorium: true, thema: 1, tekst: 3, zin: 5 },
  { grondvorm: "fabula", aanvullingen: "fabulae (v.)", vertaling: "(hier:) legende", thema: 1, tekst: 3, zin: 5 },
  { grondvorm: "tradere", aanvullingen: "trado, tradidi, traditum", vertaling: "uitleveren, overleveren", repertorium: true, thema: 1, tekst: 3, zin: 5 },
  { grondvorm: "credere", aanvullingen: "credo, credidi, creditum (+ dat)", vertaling: "1. geloven; 2. vertrouwen", repertorium: true, thema: 1, tekst: 3, zin: 6 },
  { grondvorm: "-ne", aanvullingen: "vraagpartikel", vertaling: "wordt niet vertaald", repertorium: true, thema: 1, tekst: 3, zin: 7 },
  { grondvorm: "draco", aanvullingen: "draconis (m.)", vertaling: "draak", thema: 1, tekst: 3, zin: 7 },
  { grondvorm: "aliquantulus", aanvullingen: "aliquantula, aliquantulum", vertaling: "tamelijk, klein, gering", thema: 1, tekst: 3, zin: 7 },
  { grondvorm: "gratus", aanvullingen: "grata, gratum", vertaling: "aangenaam, dankbaar", repertorium: true, thema: 1, tekst: 3, zin: 7 },
  { grondvorm: "etiamsi", aanvullingen: "vgw. (+ind. of conj.)", vertaling: "ook als, zelfs indien", repertorium: true, thema: 1, tekst: 3, zin: 7 },
  { grondvorm: "verbum", aanvullingen: "verbi (o.)", vertaling: "woord", repertorium: true, thema: 1, tekst: 3, zin: 7 },
  { grondvorm: "res", aanvullingen: "rei (v.)", vertaling: "ding, zaak", repertorium: true, thema: 1, tekst: 3, zin: 7 },
  { grondvorm: "carmen", aanvullingen: "carminis (o.)", vertaling: "lied, gedicht, gezang", repertorium: true, thema: 1, tekst: 3, zin: 7 },
  { grondvorm: "nequaquam", aanvullingen: "bijw.", vertaling: "op geen enkele manier, helemaal niet", thema: 1, tekst: 3, zin: 8 },
  { grondvorm: "contingere", aanvullingen: "contingo, contigi, contactum", vertaling: "1. aanraken, aantasten; 2. reiken tot", repertorium: true, thema: 1, tekst: 3, zin: 8 },
  { grondvorm: "clades", aanvullingen: "cladis (v.)", vertaling: "ramp", thema: 1, tekst: 3, zin: 8 },
  { grondvorm: "iucundus", aanvullingen: "iucunda, iucundum", vertaling: "aangenaam", repertorium: true, thema: 1, tekst: 3, zin: 9 },
  { grondvorm: "mos", aanvullingen: "moris (o.)", vertaling: "gebruik, gewoonte, zede", repertorium: true, thema: 1, tekst: 3, zin: 9 },
  { grondvorm: "mendax", aanvullingen: "mendacis (m.)", vertaling: "leugenaar", thema: 1, tekst: 3, zin: 9 },
  { grondvorm: "familiaris", aanvullingen: "familiaris, familiare", vertaling: "bevriend, vertrouwd", repertorium: true, thema: 1, tekst: 3, zin: 9 },
  { grondvorm: "videri", aanvullingen: "videor, visus sum", vertaling: "schijnen, blijken, lijken", repertorium: true, thema: 1, tekst: 3, zin: 9 },
  { grondvorm: "meminisse", aanvullingen: "memini + gen.", vertaling: "zich herinneren, denken aan", repertorium: true, thema: 1, tekst: 3, zin: 10 },

  // ══════════════════════════════════════════════════════════════
  // THEMA 2 – VITA AN SPECIES?
  // Tekst 1: Moretum (p.16)
  // ══════════════════════════════════════════════════════════════

  { grondvorm: "addere", aanvullingen: "addo, addidi, additum", vertaling: "toevoegen", repertorium: true, thema: 2, tekst: 1, zin: 1 },
  { grondvorm: "mortarium", aanvullingen: "mortarii (o.)", vertaling: "vijzel", thema: 2, tekst: 1, zin: 1 },
  { grondvorm: "satureia", aanvullingen: "satureiae (v.)", vertaling: "bonenkruid", thema: 2, tekst: 1, zin: 1 },
  { grondvorm: "menta", aanvullingen: "mentae (v.)", vertaling: "munt", thema: 2, tekst: 1, zin: 1 },
  { grondvorm: "ruta", aanvullingen: "rutae (v.)", vertaling: "wijnruit", thema: 2, tekst: 1, zin: 1 },
  { grondvorm: "coriandrum", aanvullingen: "coriandri (o.)", vertaling: "koriander", thema: 2, tekst: 1, zin: 1 },
  { grondvorm: "apium", aanvullingen: "api(i) (o.)", vertaling: "selderij", thema: 2, tekst: 1, zin: 1 },
  { grondvorm: "porrum", aanvullingen: "porri (o.)", vertaling: "prei", thema: 2, tekst: 1, zin: 1 },
  { grondvorm: "sectivus", aanvullingen: "sectiva, sectivum", vertaling: "gesneden", thema: 2, tekst: 1, zin: 1 },
  { grondvorm: "aut", aanvullingen: "nevensch. vgw", vertaling: "of", repertorium: true, thema: 2, tekst: 1, zin: 1 },
  { grondvorm: "si", aanvullingen: "ondersch. vgw", vertaling: "als, indien", repertorium: true, thema: 2, tekst: 1, zin: 1 },
  { grondvorm: "viridis", aanvullingen: "viridis, viride", vertaling: "1. groen; 2. jeugdig, fris; 3. krachtig", repertorium: true, thema: 2, tekst: 1, zin: 2 },
  { grondvorm: "caepa", aanvullingen: "caepae (v.)", vertaling: "ui", thema: 2, tekst: 1, zin: 2 },
  { grondvorm: "folium", aanvullingen: "folii (o.)", vertaling: "blad", repertorium: true, thema: 2, tekst: 1, zin: 2 },
  { grondvorm: "lactuca", aanvullingen: "lactucae (v.)", vertaling: "sla", thema: 2, tekst: 1, zin: 2 },
  { grondvorm: "eruca", aanvullingen: "erucae (v.)", vertaling: "rucola", thema: 2, tekst: 1, zin: 2 },
  { grondvorm: "thymum", aanvullingen: "thymi (o.)", vertaling: "tijm", thema: 2, tekst: 1, zin: 2 },
  { grondvorm: "vel", aanvullingen: "nevensch. vgw", vertaling: "of", repertorium: true, thema: 2, tekst: 1, zin: 2 },
  { grondvorm: "nepeta", aanvullingen: "nepetae (v.)", vertaling: "kattenkruid", thema: 2, tekst: 1, zin: 2 },
  { grondvorm: "etiam", aanvullingen: "bijw.", vertaling: "ook, zelfs", repertorium: true, thema: 2, tekst: 1, zin: 2 },
  { grondvorm: "puleium", aanvullingen: "puleii (o.)", vertaling: "polei", thema: 2, tekst: 1, zin: 2 },
  { grondvorm: "caseus", aanvullingen: "casei (m.)", vertaling: "kaas", thema: 2, tekst: 1, zin: 3 },
  { grondvorm: "recens", aanvullingen: "recens, recens, gen. recentis", vertaling: "nieuw, vers, pas gemaakt", repertorium: true, thema: 2, tekst: 1, zin: 3 },
  { grondvorm: "salsus", aanvullingen: "salsa, salsum", vertaling: "zout", thema: 2, tekst: 1, zin: 3 },
  { grondvorm: "is", aanvullingen: "ea, id", vertaling: "deze, die", repertorium: true, thema: 2, tekst: 1, zin: 3 },
  { grondvorm: "omnis", aanvullingen: "omnis, omne", vertaling: "geheel, ieder, (mv.) allen", repertorium: true, thema: 2, tekst: 1, zin: 3 },
  { grondvorm: "partiri", aanvullingen: "partior, partitus sum", vertaling: "verdelen", thema: 2, tekst: 1, zin: 3 },
  { grondvorm: "terere", aanvullingen: "tero, trivi, tritum", vertaling: "fijnwrijven", thema: 2, tekst: 1, zin: 3 },
  { grondvorm: "acetum", aanvullingen: "aceti (o.)", vertaling: "azijn", thema: 2, tekst: 1, zin: 3 },
  { grondvorm: "piperatus", aanvullingen: "piperata, piperatum", vertaling: "gepeperd", thema: 2, tekst: 1, zin: 3 },
  { grondvorm: "exiguus", aanvullingen: "exigua, exiguum", vertaling: "weinig, klein", thema: 2, tekst: 1, zin: 3 },
  { grondvorm: "permiscere", aanvullingen: "permisceo, permiscui, permixtum", vertaling: "mengen", thema: 2, tekst: 1, zin: 3 },
  { grondvorm: "mixtura", aanvullingen: "mixturae (v.)", vertaling: "mengsel", thema: 2, tekst: 1, zin: 4 },
  { grondvorm: "cum", aanvullingen: "(vz.) (+abl.)", vertaling: "met, samen met", repertorium: true, thema: 2, tekst: 1, zin: 4 },
  { grondvorm: "catillus", aanvullingen: "catilli (m.)", vertaling: "schaaltje", thema: 2, tekst: 1, zin: 4 },
  { grondvorm: "componere", aanvullingen: "compono, composui, compositum", vertaling: "samenstellen, veinzen", repertorium: true, thema: 2, tekst: 1, zin: 4 },
  { grondvorm: "oleum", aanvullingen: "olei (o.)", vertaling: "olie", thema: 2, tekst: 1, zin: 4 },
  { grondvorm: "superfudere", aanvullingen: "superfundo, superfudi, superfusum", vertaling: "overgieten", thema: 2, tekst: 1, zin: 4 },

  // ── Tekst 2: Isicia omentata (p.16) ──

  { grondvorm: "isicium", aanvullingen: "isicii (o.)", vertaling: "gehaktbal, worstje", thema: 2, tekst: 2, zin: 1 },
  { grondvorm: "omentatus", aanvullingen: "omentata, omentatum", vertaling: "met netvet bedekt", thema: 2, tekst: 2, zin: 1 },
  { grondvorm: "sic", aanvullingen: "bijw.", vertaling: "zo", repertorium: true, thema: 2, tekst: 2, zin: 1 },
  { grondvorm: "facere", aanvullingen: "facio, feci, factum", vertaling: "doen, maken", repertorium: true, thema: 2, tekst: 2, zin: 1 },
  { grondvorm: "caro", aanvullingen: "carnis (v.)", vertaling: "vlees", thema: 2, tekst: 2, zin: 2 },
  { grondvorm: "minutatim", aanvullingen: "bijw.", vertaling: "in kleine stukjes", thema: 2, tekst: 2, zin: 2 },
  { grondvorm: "concidere", aanvullingen: "concīdo, concidi, concisum", vertaling: "fijnsnijden", thema: 2, tekst: 2, zin: 2 },
  { grondvorm: "piper", aanvullingen: "piperis (o.)", vertaling: "peper", thema: 2, tekst: 2, zin: 3 },
  { grondvorm: "liquamen", aanvullingen: "liquaminis (o.)", vertaling: "vissaus", thema: 2, tekst: 2, zin: 3 },
  { grondvorm: "vinum", aanvullingen: "vini (o.)", vertaling: "wijn", repertorium: true, thema: 2, tekst: 2, zin: 3 },
  { grondvorm: "adicere", aanvullingen: "adicio, adieci, adiectum", vertaling: "toevoegen", repertorium: true, thema: 2, tekst: 2, zin: 3 },
  { grondvorm: "panis", aanvullingen: "panis (m.)", vertaling: "brood", thema: 2, tekst: 2, zin: 4 },
  { grondvorm: "e(x)", aanvullingen: "(vz) (+ abl.)", vertaling: "uit, van(af), (weg) van", repertorium: true, thema: 2, tekst: 2, zin: 4 },
  { grondvorm: "lac", aanvullingen: "lactis (o.)", vertaling: "melk", repertorium: true, thema: 2, tekst: 2, zin: 4 },
  { grondvorm: "maceratus", aanvullingen: "macerata, maceratum", vertaling: "geweekt", thema: 2, tekst: 2, zin: 4 },
  { grondvorm: "omentum", aanvullingen: "omenti (o.)", vertaling: "netvet", thema: 2, tekst: 2, zin: 5 },
  { grondvorm: "involvere", aanvullingen: "involvo, involvi, involutum", vertaling: "omwikkelen", thema: 2, tekst: 2, zin: 5 },
  { grondvorm: "assare", aanvullingen: "asso, assavi, assatum", vertaling: "roosteren", thema: 2, tekst: 2, zin: 5 },

  // ── Tekst 3: Pullum Frontonianum (p.17) ──

  { grondvorm: "pullus", aanvullingen: "pulli (m.)", vertaling: "kip", thema: 2, tekst: 3, zin: 1 },
  { grondvorm: "praedurus", aanvullingen: "praedura, praedurum", vertaling: "zeer hard", thema: 2, tekst: 3, zin: 1 },
  { grondvorm: "condire", aanvullingen: "condio, condidi, conditum", vertaling: "kruiden", thema: 2, tekst: 3, zin: 1 },
  { grondvorm: "miscere", aanvullingen: "misceo, miscui, mixtum", vertaling: "mengen", repertorium: true, thema: 2, tekst: 3, zin: 1 },
  { grondvorm: "mittere", aanvullingen: "mitto, misi, missum", vertaling: "1. zenden, sturen; 2. laten gaan", repertorium: true, thema: 2, tekst: 3, zin: 1 },
  { grondvorm: "fasciculus", aanvullingen: "fasciculi (m.)", vertaling: "bundeltje", thema: 2, tekst: 3, zin: 1 },
  { grondvorm: "anethum", aanvullingen: "anethi (o.)", vertaling: "dille", thema: 2, tekst: 3, zin: 1 },
  { grondvorm: "coquere", aanvullingen: "coquo, coxi, coctum", vertaling: "koken", thema: 2, tekst: 3, zin: 2 },
  { grondvorm: "ubi", aanvullingen: "ondersch. vgw (+ ind.)", vertaling: "toen, zodra", repertorium: true, thema: 2, tekst: 3, zin: 2 },
  { grondvorm: "levare", aanvullingen: "levo, levavi, levatum", vertaling: "opheffen, eruit halen", thema: 2, tekst: 3, zin: 2 },
  { grondvorm: "in", aanvullingen: "(vz.) (+ abl.)", vertaling: "in, op", repertorium: true, thema: 2, tekst: 3, zin: 2 },
  { grondvorm: "lanx", aanvullingen: "lancis (v.)", vertaling: "schaal", thema: 2, tekst: 3, zin: 2 },
  { grondvorm: "defrutum", aanvullingen: "defruti (o.)", vertaling: "ingekookte wijn", thema: 2, tekst: 3, zin: 2 },
  { grondvorm: "perungere", aanvullingen: "perungo, perunxi, perunctum", vertaling: "insmeren", thema: 2, tekst: 3, zin: 2 },
  { grondvorm: "aspargere", aanvullingen: "aspargo, aspersi, aspersum", vertaling: "erop strooien", thema: 2, tekst: 3, zin: 2 },
  { grondvorm: "inferre", aanvullingen: "infero, intuli, illatum", vertaling: "brengen in/naar, veroorzaken", repertorium: true, thema: 2, tekst: 3, zin: 2 },

  // ── Tekst 4: Epigrammen (p.18) ──

  { grondvorm: "numquam", aanvullingen: "bijw.", vertaling: "nooit", repertorium: true, thema: 2, tekst: 4, zin: 1 },
  { grondvorm: "revocare", aanvullingen: "revoco, revocavi, revocatum", vertaling: "terugroepen", thema: 2, tekst: 4, zin: 1 },
  { grondvorm: "cum", aanvullingen: "ondersch. vgw (+ind.)", vertaling: "wanneer/als", repertorium: true, thema: 2, tekst: 4, zin: 1 },
  { grondvorm: "saepe", aanvullingen: "bijw.", vertaling: "vaak, dikwijls", repertorium: true, thema: 2, tekst: 4, zin: 1 },
  { grondvorm: "ignoscere", aanvullingen: "ignosco, ignovi, ignotum", vertaling: "vergeven", thema: 2, tekst: 4, zin: 2 },
  { grondvorm: "Gallus", aanvullingen: "Galli (m.)", vertaling: "Galliër", repertorium: true, thema: 2, tekst: 4, zin: 2 },
  { grondvorm: "invitare", aanvullingen: "invito, invitavi, invitatum", vertaling: "uitnodigen", thema: 2, tekst: 4, zin: 3 },
  { grondvorm: "vitium", aanvullingen: "vitii (o.)", vertaling: "gebrek, fout", thema: 2, tekst: 4, zin: 3 },
  { grondvorm: "uterque", aanvullingen: "utraque, utrumque", vertaling: "elk van beide(n), beide(n)", repertorium: true, thema: 2, tekst: 4, zin: 3 },
  { grondvorm: "inquam", aanvullingen: "defectief ww. inquis, inquit", vertaling: "zeg jij", thema: 2, tekst: 4, zin: 3 },
  { grondvorm: "cor", aanvullingen: "cordis (o.)", vertaling: "hart", repertorium: true, thema: 2, tekst: 4, zin: 4 },
  { grondvorm: "pudor", aanvullingen: "pudoris (m.)", vertaling: "1. schaamte; 2. eergevoel; 3. verlegenheid", repertorium: true, thema: 2, tekst: 4, zin: 4 },

  // ── Tekst 5: Epigrammen deel 2 (p.18) ──

  { grondvorm: "felix", aanvullingen: "felix, felix, gen. felicis", vertaling: "gelukkig", repertorium: true, thema: 2, tekst: 5, zin: 1 },
  { grondvorm: "fieri", aanvullingen: "fio, factus sum", vertaling: "worden", repertorium: true, thema: 2, tekst: 5, zin: 1 },
  { grondvorm: "Zoilus", aanvullingen: "Zoili (m.)", vertaling: "Zoilus", thema: 2, tekst: 5, zin: 1 },
  { grondvorm: "cena", aanvullingen: "cenae (v.)", vertaling: "maaltijd", thema: 2, tekst: 5, zin: 1 },
  { grondvorm: "deinde", aanvullingen: "bijw.", vertaling: "daarna", repertorium: true, thema: 2, tekst: 5, zin: 2 },
  { grondvorm: "debere", aanvullingen: "debeo, debui, debitum", vertaling: "moeten, verschuldigd zijn", repertorium: true, thema: 2, tekst: 5, zin: 3 },
  { grondvorm: "Aricinus", aanvullingen: "Aricini (m.)", vertaling: "Aricijns", thema: 2, tekst: 5, zin: 3 },
  { grondvorm: "conviva", aanvullingen: "convivae (m.)", vertaling: "gast", thema: 2, tekst: 5, zin: 3 },
  { grondvorm: "recumbere", aanvullingen: "recumbo, recubui", vertaling: "aanliggen", thema: 2, tekst: 5, zin: 3 },
  { grondvorm: "clivus", aanvullingen: "clivi (m.)", vertaling: "helling", thema: 2, tekst: 5, zin: 3 },

  // ── Tekst 6: Een kostelijk maal deel 2 (p.28) ──

  { grondvorm: "heu", aanvullingen: "tussenwerpsel", vertaling: "ah, helaas", repertorium: true, thema: 2, tekst: 6, zin: 2 },
  { grondvorm: "promittere", aanvullingen: "promitto, promisi, promissum", vertaling: "beloven", repertorium: true, thema: 2, tekst: 6, zin: 2 },
  { grondvorm: "ad", aanvullingen: "(vz) (+acc.)", vertaling: "naar, tot, bij, met het oog op", repertorium: true, thema: 2, tekst: 6, zin: 2 },
  { grondvorm: "dicere", aanvullingen: "dico, dixi, dictum", vertaling: "1. zeggen, spreken; 2. noemen", repertorium: true, thema: 2, tekst: 6, zin: 2 },
  { grondvorm: "ius", aanvullingen: "iuris (o.)", vertaling: "recht", repertorium: true, thema: 2, tekst: 6, zin: 2 },
  { grondvorm: "as", aanvullingen: "assis (m.)", vertaling: "geld, een as", thema: 2, tekst: 6, zin: 2 },
  { grondvorm: "impendium", aanvullingen: "impendii (o.)", vertaling: "kosten, schade", thema: 2, tekst: 6, zin: 2 },
  { grondvorm: "modicus", aanvullingen: "modica, modicum", vertaling: "klein, weinig", thema: 2, tekst: 6, zin: 2 },
  { grondvorm: "parare", aanvullingen: "paro, paravi, paratum", vertaling: "klaarmaken, verwerven", repertorium: true, thema: 2, tekst: 6, zin: 3 },
  { grondvorm: "singuli", aanvullingen: "singulae, singula", vertaling: "elk afzonderlijk", repertorium: true, thema: 2, tekst: 6, zin: 3 },
  { grondvorm: "cochlea", aanvullingen: "cochleae (v.)", vertaling: "slak", thema: 2, tekst: 6, zin: 3 },
  { grondvorm: "terni", aanvullingen: "ternae, terna", vertaling: "(telkens) drie", thema: 2, tekst: 6, zin: 3 },
  { grondvorm: "ovum", aanvullingen: "ovi (o.)", vertaling: "ei", thema: 2, tekst: 6, zin: 3 },
  { grondvorm: "bini", aanvullingen: "binae, bina", vertaling: "(telkens) twee", thema: 2, tekst: 6, zin: 3 },
  { grondvorm: "(h)alica", aanvullingen: "(h)alicae (v.)", vertaling: "graan, spelt", thema: 2, tekst: 6, zin: 3 },
  { grondvorm: "nix", aanvullingen: "nicis (v.)", vertaling: "sneeuw", thema: 2, tekst: 6, zin: 3 },
  { grondvorm: "quoque", aanvullingen: "bijw.", vertaling: "ook", repertorium: true, thema: 2, tekst: 6, zin: 4 },
  { grondvorm: "computare", aanvullingen: "computo, computavi, computatum", vertaling: "optellen", thema: 2, tekst: 6, zin: 4 },
  { grondvorm: "immo", aanvullingen: "bijw.", vertaling: "zelfs", repertorium: true, thema: 2, tekst: 6, zin: 4 },
  { grondvorm: "primis", aanvullingen: "bijw.", vertaling: "vooral", thema: 2, tekst: 6, zin: 4 },
  { grondvorm: "perire", aanvullingen: "pereo, perii, peritum", vertaling: "omkomen, ten onder gaan", repertorium: true, thema: 2, tekst: 6, zin: 4 },
  { grondvorm: "ferculum", aanvullingen: "ferculi (o.)", vertaling: "gerecht", thema: 2, tekst: 6, zin: 4 },
  { grondvorm: "betaceus", aanvullingen: "betacei (m.)", vertaling: "biet", thema: 2, tekst: 6, zin: 4 },
  { grondvorm: "cucurbita", aanvullingen: "cucurbitae (v.)", vertaling: "pompoen", thema: 2, tekst: 6, zin: 4 },
  { grondvorm: "bulbus", aanvullingen: "bulbi (m.)", vertaling: "bol, ui", thema: 2, tekst: 6, zin: 4 },
  { grondvorm: "mille", aanvullingen: "telw.", vertaling: "duizend", repertorium: true, thema: 2, tekst: 6, zin: 5 },
  { grondvorm: "lautus", aanvullingen: "lauta, lautum", vertaling: "verfijnd", thema: 2, tekst: 6, zin: 5 },
  { grondvorm: "audire", aanvullingen: "audio, audivi, auditum", vertaling: "horen, aanhoren, vernemen", repertorium: true, thema: 2, tekst: 6, zin: 5 },
  { grondvorm: "comoedus", aanvullingen: "comoedi (m.)", vertaling: "komediespeler", thema: 2, tekst: 6, zin: 5 },
  { grondvorm: "lector", aanvullingen: "lectoris (m.)", vertaling: "(voor)lezer", thema: 2, tekst: 6, zin: 5 },
  { grondvorm: "lyristes", aanvullingen: "lyristae (m.)", vertaling: "luitspeler", thema: 2, tekst: 6, zin: 5 },
  { grondvorm: "liberalitas", aanvullingen: "liberalitatis (v.)", vertaling: "vrijgevigheid", thema: 2, tekst: 6, zin: 5 },
  { grondvorm: "at", aanvullingen: "nevensch. vgw.", vertaling: "maar", repertorium: true, thema: 2, tekst: 6, zin: 6 },
  { grondvorm: "apud", aanvullingen: "(vz.) (+acc.)", vertaling: "bij", repertorium: true, thema: 2, tekst: 6, zin: 6 },
  { grondvorm: "nescire", aanvullingen: "nescio, nescivi, nescitum", vertaling: "niet weten", repertorium: true, thema: 2, tekst: 6, zin: 6 },
  { grondvorm: "ostreum", aanvullingen: "ostrei (o.)", vertaling: "oester", thema: 2, tekst: 6, zin: 6 },
  { grondvorm: "vulva", aanvullingen: "vulvae (v.)", vertaling: "baarmoeder (van een zeug)", thema: 2, tekst: 6, zin: 6 },
  { grondvorm: "echinus", aanvullingen: "echini (m.)", vertaling: "zee-egel", thema: 2, tekst: 6, zin: 6 },
  { grondvorm: "Gaditana", aanvullingen: "Gaditanae (v.)", vertaling: "inwoonster van Cadiz, Spanje", thema: 2, tekst: 6, zin: 6 },
  { grondvorm: "malle", aanvullingen: "malo, malui, -", vertaling: "liever willen, verkiezen", repertorium: true, thema: 2, tekst: 6, zin: 6 },
  { grondvorm: "poena", aanvullingen: "poenae (v.)", vertaling: "straf", repertorium: true, thema: 2, tekst: 6, zin: 6 },
  { grondvorm: "durus", aanvullingen: "dura, durum", vertaling: "hard", repertorium: true, thema: 2, tekst: 6, zin: 7 },
  { grondvorm: "invidere", aanvullingen: "invideo, invidi, -", vertaling: "misgunnen", thema: 2, tekst: 6, zin: 7 },
  { grondvorm: "an", aanvullingen: "vraagpartikel", vertaling: "of", repertorium: true, thema: 2, tekst: 6, zin: 7 },
  { grondvorm: "certus", aanvullingen: "certa, certum", vertaling: "zeker", repertorium: true, thema: 2, tekst: 6, zin: 7 },
  { grondvorm: "tamen", aanvullingen: "bijw.", vertaling: "toch, nochtans", repertorium: true, thema: 2, tekst: 6, zin: 7 },
  { grondvorm: "quantum", aanvullingen: "bijw.", vertaling: "hoeveel, hoe groot", repertorium: true, thema: 2, tekst: 6, zin: 7 },
  { grondvorm: "nos", aanvullingen: "nostri of nostrum", vertaling: "wij, we, ons", repertorium: true, thema: 2, tekst: 6, zin: 7 },
  { grondvorm: "ludere", aanvullingen: "ludo, lusi, lusum", vertaling: "spelen", thema: 2, tekst: 6, zin: 7 },
  { grondvorm: "ridere", aanvullingen: "rideo, risi, risum", vertaling: "lachen", repertorium: true, thema: 2, tekst: 6, zin: 7 },
  { grondvorm: "studere", aanvullingen: "studeo, studui, -", vertaling: "studeren", repertorium: true, thema: 2, tekst: 6, zin: 8 },
  { grondvorm: "posse", aanvullingen: "possum, potui, -", vertaling: "kunnen", repertorium: true, thema: 2, tekst: 6, zin: 9 },
  { grondvorm: "apparatus", aanvullingen: "apparata, apparatum", vertaling: "schitterend, goed verzorgd", thema: 2, tekst: 6, zin: 9 },
  { grondvorm: "cenare", aanvullingen: "ceno, cenavi, cenatum", vertaling: "dineren", thema: 2, tekst: 6, zin: 9 },
  { grondvorm: "multus", aanvullingen: "multa, multum", vertaling: "veel", repertorium: true, thema: 2, tekst: 6, zin: 9 },
  { grondvorm: "nusquam", aanvullingen: "bijw.", vertaling: "nergens", thema: 2, tekst: 6, zin: 9 },
  { grondvorm: "hilarus", aanvullingen: "hilara, hilarum", vertaling: "vrolijk", thema: 2, tekst: 6, zin: 9 },
  { grondvorm: "simplicus", aanvullingen: "simplica, simplicum", vertaling: "eenvoudig", thema: 2, tekst: 6, zin: 9 },
  { grondvorm: "incautus", aanvullingen: "incauta, incautum", vertaling: "zorgeloos", thema: 2, tekst: 6, zin: 9 },

  // ── Tekst 7: Goede manieren (p.34) ──

  { grondvorm: "convivium", aanvullingen: "convivii (o.)", vertaling: "maaltijd, gastmaal", thema: 2, tekst: 7, zin: 1 },
  { grondvorm: "statim", aanvullingen: "bijw.", vertaling: "onmiddellijk, dadelijk", repertorium: true, thema: 2, tekst: 7, zin: 1 },
  { grondvorm: "(a)b", aanvullingen: "(vz) + abl.", vertaling: "van, vanaf, door", repertorium: true, thema: 2, tekst: 7, zin: 1 },
  { grondvorm: "poculum", aanvullingen: "poculi (o.)", vertaling: "beker, dronk", thema: 2, tekst: 7, zin: 1 },
  { grondvorm: "auspicari", aanvullingen: "auspicor, auspicatus sum", vertaling: "beginnen met", thema: 2, tekst: 7, zin: 1 },
  { grondvorm: "potator", aanvullingen: "potatoris (m.)", vertaling: "drinker", thema: 2, tekst: 7, zin: 1 },
  { grondvorm: "bibere", aanvullingen: "bibo, bibi, bibitum", vertaling: "drinken", thema: 2, tekst: 7, zin: 1 },
  { grondvorm: "solere", aanvullingen: "soleo, solitus sum", vertaling: "gewoon zijn (te)", repertorium: true, thema: 2, tekst: 7, zin: 1 },
  { grondvorm: "summus", aanvullingen: "summa, summum", vertaling: "hoogste, de top van", repertorium: true, thema: 2, tekst: 7, zin: 9 },
  { grondvorm: "experiri", aanvullingen: "experior, expertus sum", vertaling: "proberen, ervaren, ondervinden", repertorium: true, thema: 2, tekst: 7, zin: 9 },
  { grondvorm: "post(ea)", aanvullingen: "bijw.", vertaling: "nadien, later", repertorium: true, thema: 2, tekst: 7, zin: 10 },
  { grondvorm: "potius", aanvullingen: "bijw.", vertaling: "liever", thema: 2, tekst: 7, zin: 10 },
  { grondvorm: "excusare", aanvullingen: "excuso, excusavi, excusatum", vertaling: "verontschuldigen", thema: 2, tekst: 7, zin: 10 },
  { grondvorm: "semper", aanvullingen: "bijw.", vertaling: "altijd", repertorium: true, thema: 2, tekst: 7, zin: 10 },
  { grondvorm: "valere", aanvullingen: "valeo, valui, valitum", vertaling: "gezond zijn", repertorium: true, thema: 2, tekst: 7, zin: 11 },
  { grondvorm: "solum", aanvullingen: "bijw.", vertaling: "alleen, slechts", repertorium: true, thema: 2, tekst: 7, zin: 2 },
  { grondvorm: "inhonestus", aanvullingen: "inhonesta, inhonestum", vertaling: "schandelijk, onfatsoenlijk", thema: 2, tekst: 7, zin: 2 },
  { grondvorm: "verum … etiam", aanvullingen: "bijw./conj.", vertaling: "maar ook", thema: 2, tekst: 7, zin: 2 },
  { grondvorm: "officere", aanvullingen: "officio, offeci, offectum", vertaling: "schaden, belemmeren", thema: 2, tekst: 7, zin: 2 },
  { grondvorm: "corpus", aanvullingen: "corporis (o.)", vertaling: "lichaam", repertorium: true, thema: 2, tekst: 7, zin: 2 },
  { grondvorm: "valetudo", aanvullingen: "valetudinis (v.)", vertaling: "gezondheidstoestand, gezondheid", repertorium: true, thema: 2, tekst: 7, zin: 2 },
  { grondvorm: "post", aanvullingen: "(vz.) (+acc.)", vertaling: "achter, na", repertorium: true, thema: 2, tekst: 7, zin: 2 },
  { grondvorm: "sumere", aanvullingen: "sumo, sumpsi, sumptum", vertaling: "nemen, opnemen", repertorium: true, thema: 2, tekst: 7, zin: 3 },
  { grondvorm: "ex", aanvullingen: "(vz.) (+abl.)", vertaling: "uit, van(af)", repertorium: true, thema: 2, tekst: 7, zin: 3 },
  { grondvorm: "offa", aanvullingen: "offae (v.)", vertaling: "brok, hap", thema: 2, tekst: 7, zin: 3 },
  { grondvorm: "multo", aanvullingen: "bijw.", vertaling: "veel, zeer", repertorium: true, thema: 2, tekst: 7, zin: 3 },
  { grondvorm: "minus", aanvullingen: "bijw.", vertaling: "minder", thema: 2, tekst: 7, zin: 3 },
  { grondvorm: "esus", aanvullingen: "esus (m.)", vertaling: "het eten", thema: 2, tekst: 7, zin: 3 },
  { grondvorm: "puer", aanvullingen: "pueri (m.)", vertaling: "jongen", repertorium: true, thema: 2, tekst: 7, zin: 3 },
  { grondvorm: "se", aanvullingen: "refl. vnw.", vertaling: "zich", repertorium: true, thema: 2, tekst: 7, zin: 3 },
  { grondvorm: "pius", aanvullingen: "pia, pium", vertaling: "plichtsgetrouw, vroom", repertorium: true, thema: 2, tekst: 7, zin: 3 },
  { grondvorm: "bis", aanvullingen: "bijw.", vertaling: "tweemaal", repertorium: true, thema: 2, tekst: 7, zin: 3 },
  { grondvorm: "decorus", aanvullingen: "decora, decorum", vertaling: "passend, betamelijk", thema: 2, tekst: 7, zin: 4 },
  { grondvorm: "salubris", aanvullingen: "salubris, salubre", vertaling: "gezond, heilzaam", thema: 2, tekst: 7, zin: 4 },
  { grondvorm: "semel", aanvullingen: "bijw.", vertaling: "eenmaal", repertorium: true, thema: 2, tekst: 7, zin: 5 },
  { grondvorm: "aliquandiu", aanvullingen: "bijw.", vertaling: "een tijdlang", thema: 2, tekst: 7, zin: 5 },
  { grondvorm: "pascere", aanvullingen: "pasco, pavi, pastum", vertaling: "laten grazen, voeden", repertorium: true, thema: 2, tekst: 7, zin: 5 },
  { grondvorm: "de", aanvullingen: "(vz.) (+abl.)", vertaling: "over, vanaf, van", repertorium: true, thema: 2, tekst: 7, zin: 5 },
  { grondvorm: "secundus", aanvullingen: "secunda, secundum", vertaling: "tweede", repertorium: true, thema: 2, tekst: 7, zin: 5 },
  { grondvorm: "missus", aanvullingen: "missus (m.)", vertaling: "gang (bij een maaltijd)", thema: 2, tekst: 7, zin: 5 },
  { grondvorm: "praesertim", aanvullingen: "bijw.", vertaling: "voornamelijk, in het bijzonder", thema: 2, tekst: 7, zin: 5 },
  { grondvorm: "siccus", aanvullingen: "sicca, siccum", vertaling: "droog", thema: 2, tekst: 7, zin: 5 },
  { grondvorm: "sub", aanvullingen: "(vz.) (+abl.)", vertaling: "onder, aan de voet van", repertorium: true, thema: 2, tekst: 7, zin: 5 },
  { grondvorm: "finis", aanvullingen: "finis (m.)", vertaling: "einde, grens", repertorium: true, thema: 2, tekst: 7, zin: 5 },
  { grondvorm: "modice", aanvullingen: "bijw.", vertaling: "matig, met mate", thema: 2, tekst: 7, zin: 6 },
  { grondvorm: "sorbere", aanvullingen: "sorbeo, sorbui, -", vertaling: "slurpen, opdrinken", thema: 2, tekst: 7, zin: 6 },
  { grondvorm: "ingurgitare", aanvullingen: "ingurgito, ingurgitavi, ingurgitatum", vertaling: "gulzig naar binnen gieten", thema: 2, tekst: 7, zin: 6 },
  { grondvorm: "equus", aanvullingen: "equi (m.)", vertaling: "paard", repertorium: true, thema: 2, tekst: 7, zin: 6 },
  { grondvorm: "sonitus", aanvullingen: "sonitus (m.)", vertaling: "klank, geluid", repertorium: true, thema: 2, tekst: 7, zin: 6 },
  { grondvorm: "cervisia", aanvullingen: "cervisiae (v.)", vertaling: "bier", thema: 2, tekst: 7, zin: 6 },
  { grondvorm: "nihil", aanvullingen: "nullius rei", vertaling: "niets", repertorium: true, thema: 2, tekst: 7, zin: 6 },
  { grondvorm: "quam", aanvullingen: "bijw.", vertaling: "dan (na comparatief); hoe", repertorium: true, thema: 2, tekst: 7, zin: 6 },
  { grondvorm: "inebriare", aanvullingen: "inebrio, inebriavi, inebriatum", vertaling: "dronken maken", thema: 2, tekst: 7, zin: 7 },
  { grondvorm: "ut", aanvullingen: "(vgw.) (+ind.)", vertaling: "toen, zodra, zoals", repertorium: true, thema: 2, tekst: 7, zin: 7 },
  { grondvorm: "laedere", aanvullingen: "laedo, laesi, laesum", vertaling: "kwetsen, schaden", thema: 2, tekst: 7, zin: 7 },
  { grondvorm: "dedecorare", aanvullingen: "dedecoro, dedecoravi, dedecoratum", vertaling: "onteren, in diskrediet brengen", thema: 2, tekst: 7, zin: 7 },
  { grondvorm: "aqua", aanvullingen: "aquae (v.)", vertaling: "water", repertorium: true, thema: 2, tekst: 7, zin: 7 },
  { grondvorm: "fervidus", aanvullingen: "fervida, fervidum", vertaling: "heet, gloeiend", thema: 2, tekst: 7, zin: 7 },
  { grondvorm: "convenire", aanvullingen: "convenio, conveni, conventum", vertaling: "samenkomen, overeenkomen, passen", repertorium: true, thema: 2, tekst: 7, zin: 7 },
  { grondvorm: "aetas", aanvullingen: "aetatis (v.)", vertaling: "leeftijd, tijdperk", repertorium: true, thema: 2, tekst: 7, zin: 7 },
  { grondvorm: "pati", aanvullingen: "patior, passus sum", vertaling: "lijden, ondergaan, dulden, toestaan", repertorium: true, thema: 2, tekst: 7, zin: 8 },
  { grondvorm: "sive", aanvullingen: "vgw.", vertaling: "of indien, hetzij", repertorium: true, thema: 2, tekst: 7, zin: 8 },
  { grondvorm: "regio", aanvullingen: "regionis (v.)", vertaling: "streek, gebied", repertorium: true, thema: 2, tekst: 7, zin: 8 },
  { grondvorm: "qualitas", aanvullingen: "qualitatis (v.)", vertaling: "kwaliteit, eigenschap", thema: 2, tekst: 7, zin: 8 },
  { grondvorm: "causa", aanvullingen: "causae (v.)", vertaling: "oorzaak, reden", repertorium: true, thema: 2, tekst: 7, zin: 8 },
  { grondvorm: "tenuis", aanvullingen: "tenuis, tenue", vertaling: "dun, fijn, tenger", repertorium: true, thema: 2, tekst: 7, zin: 8 },
  { grondvorm: "uti", aanvullingen: "utor, usus sum (+abl.)", vertaling: "gebruiken, omgaan met", repertorium: true, thema: 2, tekst: 7, zin: 8 },
  { grondvorm: "ardere", aanvullingen: "ardeo, arsi, -", vertaling: "branden, gloeien", repertorium: true, thema: 2, tekst: 7, zin: 8 },
  { grondvorm: "diluere", aanvullingen: "diluo, dilui, dilutum", vertaling: "oplossen, verdunnen", thema: 2, tekst: 7, zin: 9 },

  // ── Tekst 8: Waardeloos spul (p.46) ──

  { grondvorm: "materia", aanvullingen: "materiae (v.)", vertaling: "(grond)stof, materiaal, voorraad, onderwerp", repertorium: true, thema: 2, tekst: 8, zin: 1 },
  { grondvorm: "luxuria", aanvullingen: "luxuriae (v.)", vertaling: "weeldezucht, pronkzucht", repertorium: true, thema: 2, tekst: 8, zin: 1 },
  { grondvorm: "cunctus", aanvullingen: "cuncta, cunctum", vertaling: "geheel, (mv.) alle(n), alles", repertorium: true, thema: 2, tekst: 8, zin: 1 },
  { grondvorm: "maxime", aanvullingen: "bijw.", vertaling: "het meest, vooral", thema: 2, tekst: 8, zin: 1 },
  { grondvorm: "supervacuus", aanvullingen: "supervacua, supervacuum", vertaling: "overbodig, onnodig, overtollig", repertorium: true, thema: 2, tekst: 8, zin: 1 },
  { grondvorm: "margarita", aanvullingen: "margaritae (v.)", vertaling: "parel", thema: 2, tekst: 8, zin: 1 },
  { grondvorm: "enim", aanvullingen: "vgw.", vertaling: "immers, want", repertorium: true, thema: 2, tekst: 8, zin: 1 },
  { grondvorm: "gemma", aanvullingen: "gemmae (v.)", vertaling: "edelsteen, edelgesteente", thema: 2, tekst: 8, zin: 1 },
  { grondvorm: "heres", aanvullingen: "heredis (m./v.)", vertaling: "erfgenaam", thema: 2, tekst: 8, zin: 1 },
  { grondvorm: "transire", aanvullingen: "transeo, transii, transitum", vertaling: "overgaan, oversteken, voorbijgaan", repertorium: true, thema: 2, tekst: 8, zin: 2 },
  { grondvorm: "vestis", aanvullingen: "vestis (v.)", vertaling: "kleed", repertorium: true, thema: 2, tekst: 8, zin: 2 },
  { grondvorm: "prorogare", aanvullingen: "prorogo, prorogavi, prorogatum", vertaling: "verlengen, uitstellen", thema: 2, tekst: 8, zin: 2 },
  { grondvorm: "unguentum", aanvullingen: "unguenti (o.)", vertaling: "zalf, parfum", thema: 2, tekst: 8, zin: 2 },
  { grondvorm: "ilico", aanvullingen: "bijw.", vertaling: "onmiddellijk, op de plek zelf", thema: 2, tekst: 8, zin: 2 },
  { grondvorm: "exspirare", aanvullingen: "exspiro, exspiravi, exspiratum", vertaling: "uitwasemen, vervliegen", thema: 2, tekst: 8, zin: 2 },
  { grondvorm: "suus", aanvullingen: "sua, suum", vertaling: "zijn, haar, hun (bezitt. vnw.)", repertorium: true, thema: 2, tekst: 8, zin: 2 },
  { grondvorm: "mori", aanvullingen: "morior, mortuus sum", vertaling: "sterven", repertorium: true, thema: 2, tekst: 8, zin: 2 },
  { grondvorm: "hora", aanvullingen: "horae (v.)", vertaling: "uur, tijd", repertorium: true, thema: 2, tekst: 8, zin: 2 },
  { grondvorm: "commendatio", aanvullingen: "commendationis (v.)", vertaling: "aanbeveling, lofprijzing", thema: 2, tekst: 8, zin: 3 },
  { grondvorm: "ut", aanvullingen: "(vgw.) (+conj.)", vertaling: "dat, zodat, opdat", repertorium: true, thema: 2, tekst: 8, zin: 3 },
  { grondvorm: "femina", aanvullingen: "feminae (v.)", vertaling: "vrouw", repertorium: true, thema: 2, tekst: 8, zin: 3 },
  { grondvorm: "odor", aanvullingen: "odoris (m.)", vertaling: "geur", thema: 2, tekst: 8, zin: 3 },
  { grondvorm: "agere", aanvullingen: "ago, egi, actum", vertaling: "drijven, voeren, leiden, doen", repertorium: true, thema: 2, tekst: 8, zin: 3 },
  { grondvorm: "excedere", aanvullingen: "excedo, excessi, excessum", vertaling: "weggaan uit, te buiten gaan", repertorium: true, thema: 2, tekst: 8, zin: 3 },
  { grondvorm: "quadringeni", aanvullingen: "quadrigenae, quadringena", vertaling: "vierhonderd (per stuk)", thema: 2, tekst: 8, zin: 4 },
  { grondvorm: "denarius", aanvullingen: "denarii (m.)", vertaling: "denarius (Romeinse munt)", thema: 2, tekst: 8, zin: 4 },
  { grondvorm: "libra", aanvullingen: "librae (v.)", vertaling: "pond (gewicht, ca. 327 g)", thema: 2, tekst: 8, zin: 4 },
  { grondvorm: "tantus", aanvullingen: "tanta, tantum", vertaling: "zo groot", repertorium: true, thema: 2, tekst: 8, zin: 4 },
  { grondvorm: "emere", aanvullingen: "emo, emi, emptum", vertaling: "kopen", repertorium: true, thema: 2, tekst: 8, zin: 4 },
  { grondvorm: "voluptas", aanvullingen: "voluptatis (v.)", vertaling: "genot, genoegen", thema: 2, tekst: 8, zin: 4 },
  { grondvorm: "alienus", aanvullingen: "aliena, alienum", vertaling: "vreemd, andermans, van een ander", repertorium: true, thema: 2, tekst: 8, zin: 4 },
  { grondvorm: "etenim", aanvullingen: "vgw.", vertaling: "want immers, want", repertorium: true, thema: 2, tekst: 8, zin: 4 },
  { grondvorm: "gerere", aanvullingen: "gero, gessi, gestum", vertaling: "dragen, voeren, maken, doen", repertorium: true, thema: 2, tekst: 8, zin: 4 },

  // ── Tekst 9: Vreemd geurtje (p.50) ──

  { grondvorm: "quod", aanvullingen: "(vgw.) (+ind.)", vertaling: "dat, omdat", repertorium: true, thema: 2, tekst: 9, zin: 1 },
  { grondvorm: "quicumque", aanvullingen: "quaecumque, quodcumque", vertaling: "om het even wie, wat, welke", repertorium: true, thema: 2, tekst: 9, zin: 1 },
  { grondvorm: "Cosmus", aanvullingen: "Cosmi (m.)", vertaling: "Cosmus (bekende parfumeur in Rome)", thema: 2, tekst: 9, zin: 1 },
  { grondvorm: "migrare", aanvullingen: "migro, migravi, migratum", vertaling: "verhuizen, overgaan", thema: 2, tekst: 9, zin: 1 },
  { grondvorm: "putare", aanvullingen: "puto, putavi, putatum", vertaling: "menen, denken, achten", repertorium: true, thema: 2, tekst: 9, zin: 1 },
  { grondvorm: "fluere", aanvullingen: "fluo, fluxi, fluxum", vertaling: "vloeien, stromen", thema: 2, tekst: 9, zin: 2 },
  { grondvorm: "excutere", aanvullingen: "excutio, excussi, excussum", vertaling: "uitschudden, losschudden", thema: 2, tekst: 9, zin: 2 },
  { grondvorm: "cinnamum", aanvullingen: "cinnami (o.)", vertaling: "kaneel", thema: 2, tekst: 9, zin: 2 },
  { grondvorm: "fundere", aanvullingen: "fundo, fudi, fusum", vertaling: "gieten, uitstorten", thema: 2, tekst: 9, zin: 2 },
  { grondvorm: "vitrum", aanvullingen: "vitri (o.)", vertaling: "glas", thema: 2, tekst: 9, zin: 2 },
  { grondvorm: "nolle", aanvullingen: "nolo, nolui, -", vertaling: "niet willen", repertorium: true, thema: 2, tekst: 9, zin: 3 },
  { grondvorm: "peregrinus", aanvullingen: "peregrina, peregrinum", vertaling: "buitenlands, vreemd", thema: 2, tekst: 9, zin: 3 },
  { grondvorm: "placere", aanvullingen: "placeo, placui, placitum", vertaling: "bevallen, behagen", repertorium: true, thema: 2, tekst: 9, zin: 3 },
  { grondvorm: "nugae", aanvullingen: "nugarum (v. mv.)", vertaling: "beuzelarijen, onzin", thema: 2, tekst: 9, zin: 3 },
  { grondvorm: "scire", aanvullingen: "scio, scivi, scitum", vertaling: "weten", repertorium: true, thema: 2, tekst: 9, zin: 4 },
  { grondvorm: "meus", aanvullingen: "mea, meum", vertaling: "mijn", repertorium: true, thema: 2, tekst: 9, zin: 4 },
  { grondvorm: "bene", aanvullingen: "bijw.", vertaling: "goed", repertorium: true, thema: 2, tekst: 9, zin: 4 },
  { grondvorm: "olere", aanvullingen: "oleo, olui, -", vertaling: "ruiken, geuren", thema: 2, tekst: 9, zin: 4 },
  { grondvorm: "canis", aanvullingen: "canis (m./v.)", vertaling: "hond", repertorium: true, thema: 2, tekst: 9, zin: 4 },

  // ── Tekst 10: Ik wil jou naturel! (p.54) ──

  { grondvorm: "desinere", aanvullingen: "desino, desii, desitum", vertaling: "ophouden, stoppen", thema: 2, tekst: 10, zin: 1 },
  { grondvorm: "tener", aanvullingen: "tenera, tenerum", vertaling: "teer, fijn, jong", repertorium: true, thema: 2, tekst: 10, zin: 1 },
  { grondvorm: "crinis", aanvullingen: "crinis (m.)", vertaling: "haar, haarlok", thema: 2, tekst: 10, zin: 1 },
  { grondvorm: "ornare", aanvullingen: "orno, ornavi, ornatum", vertaling: "sieren, versieren, tooien", thema: 2, tekst: 10, zin: 1 },
  { grondvorm: "puella", aanvullingen: "puellae (v.)", vertaling: "meisje", repertorium: true, thema: 2, tekst: 10, zin: 1 },
  { grondvorm: "pexus", aanvullingen: "pexa, pexum", vertaling: "gekamd, verzorgd", thema: 2, tekst: 10, zin: 2 },
  { grondvorm: "ligare", aanvullingen: "ligo, ligavi, ligatum", vertaling: "binden, vastbinden", thema: 2, tekst: 10, zin: 2 },
  { grondvorm: "coma", aanvullingen: "comae (v.)", vertaling: "haar, haartooi", thema: 2, tekst: 10, zin: 2 },
  { grondvorm: "diffluere", aanvullingen: "diffluo, diffluxi, -", vertaling: "uitstromen, los hangen", thema: 2, tekst: 10, zin: 3 },
  { grondvorm: "vagus", aanvullingen: "vaga, vagum", vertaling: "zwervend, los, vrij", thema: 2, tekst: 10, zin: 3 },
  { grondvorm: "circum", aanvullingen: "(vz.) (+acc.)", vertaling: "rond, rondom, langs", repertorium: true, thema: 2, tekst: 10, zin: 3 },
  { grondvorm: "tempus", aanvullingen: "temporis (o.)", vertaling: "1. tijd, tijdstip; 2. hier: slaap (van het hoofd)", repertorium: true, thema: 2, tekst: 10, zin: 3 },
  { grondvorm: "mollis", aanvullingen: "mollis, molle", vertaling: "zacht, week", repertorium: true, thema: 2, tekst: 10, zin: 4 },
  { grondvorm: "per", aanvullingen: "(vz.) (+acc.)", vertaling: "1. door(...heen); 2. gedurende; 3. door toedoen van", repertorium: true, thema: 2, tekst: 10, zin: 4 },
  { grondvorm: "collum", aanvullingen: "colli (o.)", vertaling: "hals, nek", repertorium: true, thema: 2, tekst: 10, zin: 4 },
  { grondvorm: "cultus", aanvullingen: "cultus (m.)", vertaling: "1. verzorging; 2. verfijning; 3. beschaving", repertorium: true, thema: 2, tekst: 10, zin: 5 },
  { grondvorm: "labellum", aanvullingen: "labelli (o.)", vertaling: "lipje", thema: 2, tekst: 10, zin: 5 },
  { grondvorm: "lascivus", aanvullingen: "lasciva, lascivum", vertaling: "speels, dartel, wulps", thema: 2, tekst: 10, zin: 6 },
  { grondvorm: "oculus", aanvullingen: "oculi (m.)", vertaling: "oog", repertorium: true, thema: 2, tekst: 10, zin: 6 },
  { grondvorm: "modus", aanvullingen: "modi (m.)", vertaling: "1. manier, wijze; 2. maat", repertorium: true, thema: 2, tekst: 10, zin: 6 },
  { grondvorm: "ornatus", aanvullingen: "ornatus (m.)", vertaling: "versiering, tooi, sieraad", thema: 2, tekst: 10, zin: 7 },
  { grondvorm: "os", aanvullingen: "oris (o.)", vertaling: "1. mond, muil; 2. gelaat, hoofd", repertorium: true, thema: 2, tekst: 10, zin: 8 },
  { grondvorm: "comptus", aanvullingen: "compta, comptum", vertaling: "gekamd, getooid, verzorgd", thema: 2, tekst: 10, zin: 9 },
  { grondvorm: "placidus", aanvullingen: "placida, placidum", vertaling: "kalm, vriendelijk, zacht", thema: 2, tekst: 10, zin: 9 },
  { grondvorm: "accedere", aanvullingen: "accedo, accessi, accessum", vertaling: "gaan naar, naderen", repertorium: true, thema: 2, tekst: 10, zin: 9 },
  { grondvorm: "ocellus", aanvullingen: "ocelli (m.)", vertaling: "oogje", thema: 2, tekst: 10, zin: 9 },
  { grondvorm: "obtutus", aanvullingen: "obtutus (m.)", vertaling: "blik, aanblik", thema: 2, tekst: 10, zin: 10 },
  { grondvorm: "comes", aanvullingen: "comitis (m./v.)", vertaling: "begeleider, gezel", repertorium: true, thema: 2, tekst: 10, zin: 10 },
  { grondvorm: "usque", aanvullingen: "bijw.", vertaling: "voortdurend, steeds", thema: 2, tekst: 10, zin: 10 },
  { grondvorm: "velle", aanvullingen: "volo, volui, -", vertaling: "willen", repertorium: true, thema: 2, tekst: 10, zin: 10 },
  { grondvorm: "facies", aanvullingen: "faciei (v.)", vertaling: "1. uiterlijk, aanblik; 2. gelaat", repertorium: true, thema: 2, tekst: 10, zin: 11 },
  { grondvorm: "simul", aanvullingen: "bijw.", vertaling: "tegelijk, samen", repertorium: true, thema: 2, tekst: 10, zin: 11 },
  { grondvorm: "compere", aanvullingen: "como, compsi, comptum", vertaling: "kamen, tooien, sieren", thema: 2, tekst: 10, zin: 11 },
  { grondvorm: "suspirare", aanvullingen: "suspiro, suspiravi, suspiratum", vertaling: "zuchten, zware ademhalen", thema: 2, tekst: 10, zin: 12 },
  { grondvorm: "quotiens", aanvullingen: "bijw.", vertaling: "1. hoe vaak; 2. telkens als", repertorium: true, thema: 2, tekst: 10, zin: 12 },
  { grondvorm: "obvius", aanvullingen: "obvia, obvium", vertaling: "tegemoetkomend, op de weg", thema: 2, tekst: 10, zin: 12 },
  { grondvorm: "amans", aanvullingen: "amantis (m./v.)", vertaling: "minnaar, geliefde", thema: 2, tekst: 10, zin: 12 },

  // ══════════════════════════════════════════════════════════════
  // THEMA 3 – PANEM ET CIRCENSES
  // Tekst 1: Stom tijdverdrijf (p.18)
  // ══════════════════════════════════════════════════════════════

  { grondvorm: "inter", aanvullingen: "(vz.) (+acc.)", vertaling: "1. tussen, te midden van; 2. onder", repertorium: true, thema: 3, tekst: 1, zin: 2 },
  { grondvorm: "pugillares", aanvullingen: "pugillarium (m. mv.)", vertaling: "schrijftabletten", thema: 3, tekst: 1, zin: 2 },
  { grondvorm: "libellus", aanvullingen: "libelli (m.)", vertaling: "boekje, geschriftje", thema: 3, tekst: 1, zin: 2 },
  { grondvorm: "quies", aanvullingen: "quietis (v.)", vertaling: "rust", repertorium: true, thema: 3, tekst: 1, zin: 2 },
  { grondvorm: "transmittere", aanvullingen: "transmitto, transmisi, transmissum", vertaling: "1. doorbrengen; 2. oversteken", thema: 3, tekst: 1, zin: 2 },
  { grondvorm: "quemadmodum", aanvullingen: "bijw.", vertaling: "op welke manier, hoe", repertorium: true, thema: 3, tekst: 1, zin: 2 },
  { grondvorm: "urbs", aanvullingen: "urbis (v.)", vertaling: "stad", repertorium: true, thema: 3, tekst: 1, zin: 3 },
  { grondvorm: "circenses", aanvullingen: "circensium (m. mv.)", vertaling: "circusspelen", thema: 3, tekst: 1, zin: 3 },
  { grondvorm: "genus", aanvullingen: "generis (o.)", vertaling: "1. geslacht, soort; 2. afkomst, familie", repertorium: true, thema: 3, tekst: 1, zin: 3 },
  { grondvorm: "spectaculum", aanvullingen: "spectaculi (o.)", vertaling: "schouwspel, voorstelling", repertorium: true, thema: 3, tekst: 1, zin: 3 },
  { grondvorm: "levis", aanvullingen: "levis, leve", vertaling: "licht (niet zwaar)", repertorium: true, thema: 3, tekst: 1, zin: 3 },
  { grondvorm: "quidem", aanvullingen: "bijw.", vertaling: "zeker, althans, tenminste, echter, en dan nog", repertorium: true, thema: 3, tekst: 1, zin: 3 },
  { grondvorm: "novus", aanvullingen: "nova, novum", vertaling: "nieuw", repertorium: true, thema: 3, tekst: 1, zin: 4 },
  { grondvorm: "varius", aanvullingen: "varia, varium", vertaling: "afwisselend, verschillend", repertorium: true, thema: 3, tekst: 1, zin: 4 },
  { grondvorm: "spectare", aanvullingen: "specto, spectavi, spectatum", vertaling: "kijken, bekijken", repertorium: true, thema: 3, tekst: 1, zin: 4 },
  { grondvorm: "sufficere", aanvullingen: "sufficio, suffeci, suffectum", vertaling: "voldoende zijn, volstaan", thema: 3, tekst: 1, zin: 4 },
  { grondvorm: "magis", aanvullingen: "bijw.", vertaling: "meer", repertorium: true, thema: 3, tekst: 1, zin: 4 },
  { grondvorm: "mirari", aanvullingen: "miror, miratus sum", vertaling: "1. zich verwonderen; 2. bewonderen", repertorium: true, thema: 3, tekst: 1, zin: 4 },
  { grondvorm: "tot", aanvullingen: "bijw.", vertaling: "zoveel", repertorium: true, thema: 3, tekst: 1, zin: 4 },
  { grondvorm: "vir", aanvullingen: "viri (m.)", vertaling: "man", repertorium: true, thema: 3, tekst: 1, zin: 5 },
  { grondvorm: "pueriliter", aanvullingen: "bijw.", vertaling: "kinderlijk, als een kind", thema: 3, tekst: 1, zin: 5 },
  { grondvorm: "identidem", aanvullingen: "bijw.", vertaling: "telkens, herhaaldelijk", thema: 3, tekst: 1, zin: 5 },
  { grondvorm: "currere", aanvullingen: "curro, cucurri, cursum", vertaling: "lopen, rennen", repertorium: true, thema: 3, tekst: 1, zin: 5 },
  { grondvorm: "insistere", aanvullingen: "insisto, institi, -", vertaling: "staan op, staan in", thema: 3, tekst: 1, zin: 5 },
  { grondvorm: "currus", aanvullingen: "currus (m.)", vertaling: "wagen, renwagen, strijdwagen", repertorium: true, thema: 3, tekst: 1, zin: 5 },
  { grondvorm: "homo", aanvullingen: "hominis (m.)", vertaling: "mens", repertorium: true, thema: 3, tekst: 1, zin: 5 },
  { grondvorm: "videre", aanvullingen: "video, vidi, visum", vertaling: "zien", repertorium: true, thema: 3, tekst: 1, zin: 5 },
  { grondvorm: "velocitas", aanvullingen: "velocitatis (v.)", vertaling: "snelheid", thema: 3, tekst: 1, zin: 6 },
  { grondvorm: "trahere", aanvullingen: "traho, traxi, tractum", vertaling: "trekken, slepen", repertorium: true, thema: 3, tekst: 1, zin: 6 },
  { grondvorm: "ratio", aanvullingen: "rationis (v.)", vertaling: "1. (be)rekening; 2. verstand; 3. redenering, reden", repertorium: true, thema: 3, tekst: 1, zin: 6 },
  { grondvorm: "favere", aanvullingen: "faveo, favi, fautum (+ dat.)", vertaling: "gunstig gezind zijn, toejuichen", thema: 3, tekst: 1, zin: 6 },
  { grondvorm: "pannus", aanvullingen: "panni (m.)", vertaling: "lap stof, kleur (van een renstal)", thema: 3, tekst: 1, zin: 6 },
  { grondvorm: "amare", aanvullingen: "amo, amavi, amatum", vertaling: "beminnen, houden van", repertorium: true, thema: 3, tekst: 1, zin: 7 },
  { grondvorm: "cursus", aanvullingen: "cursus (m.)", vertaling: "het lopen, wedloop, loopbaan, carrière", repertorium: true, thema: 3, tekst: 1, zin: 7 },
  { grondvorm: "medius", aanvullingen: "media, medium", vertaling: "middelste, in het midden van", repertorium: true, thema: 3, tekst: 1, zin: 7 },
  { grondvorm: "certamen", aanvullingen: "certaminis (o.)", vertaling: "1. wedstrijd; 2. strijd, gevecht", repertorium: true, thema: 3, tekst: 1, zin: 7 },
  { grondvorm: "color", aanvullingen: "coloris (m.)", vertaling: "kleur", repertorium: true, thema: 3, tekst: 1, zin: 7 },
  { grondvorm: "illuc", aanvullingen: "bijw.", vertaling: "daarheen", repertorium: true, thema: 3, tekst: 1, zin: 7 },
  { grondvorm: "transferre", aanvullingen: "transfero, transtuli, translatum", vertaling: "overbrengen", repertorium: true, thema: 3, tekst: 1, zin: 7 },
  { grondvorm: "studium", aanvullingen: "studii (o.)", vertaling: "1. ijver, voorkeur, studie; 2. belangstelling", repertorium: true, thema: 3, tekst: 1, zin: 7 },
  { grondvorm: "favor", aanvullingen: "favoris (m.)", vertaling: "goedgunst, bijval, toegenegenheid", thema: 3, tekst: 1, zin: 8 },
  { grondvorm: "repente", aanvullingen: "bijw.", vertaling: "plots", repertorium: true, thema: 3, tekst: 1, zin: 8 },
  { grondvorm: "agitator", aanvullingen: "agitatoris (m.)", vertaling: "wagenmenner", thema: 3, tekst: 1, zin: 8 },
  { grondvorm: "procul", aanvullingen: "bijw.", vertaling: "ver, in de verte, van ver", repertorium: true, thema: 3, tekst: 1, zin: 8 },
  { grondvorm: "noscere", aanvullingen: "nosco, novi, notum", vertaling: "leren kennen, kennen (vlt. tijden)", repertorium: true, thema: 3, tekst: 1, zin: 8 },
  { grondvorm: "clamitare", aanvullingen: "clamito, clamitavi, clamitatum", vertaling: "voortdurend roepen, schreeuwen", thema: 3, tekst: 1, zin: 8 },
  { grondvorm: "nomen", aanvullingen: "nominis (o.)", vertaling: "naam", repertorium: true, thema: 3, tekst: 1, zin: 8 },
  { grondvorm: "relinquere", aanvullingen: "relinquo, reliqui, relictum", vertaling: "achterlaten, verlaten", repertorium: true, thema: 3, tekst: 1, zin: 9 },
  { grondvorm: "auctoritas", aanvullingen: "auctoritatis (v.)", vertaling: "gezag, aanzien", repertorium: true, thema: 3, tekst: 1, zin: 9 },
  { grondvorm: "unus", aanvullingen: "una, unum", vertaling: "één", repertorium: true, thema: 3, tekst: 1, zin: 9 },
  { grondvorm: "vilis", aanvullingen: "vilis, vile", vertaling: "1. goedkoop, waardeloos; 2. verachtelijk", repertorium: true, thema: 3, tekst: 1, zin: 9 },
  { grondvorm: "tunica", aanvullingen: "tunicae (v.)", vertaling: "tuniek, (rens)kleur", thema: 3, tekst: 1, zin: 9 },
  { grondvorm: "vulgus", aanvullingen: "vulgi (o.)", vertaling: "het volk, het publiek", repertorium: true, thema: 3, tekst: 1, zin: 10 },
  { grondvorm: "quidam", aanvullingen: "quaedam, quoddam", vertaling: "1. een zekere; 2. iemand, iets", repertorium: true, thema: 3, tekst: 1, zin: 10 },
  { grondvorm: "gravis", aanvullingen: "gravis, grave", vertaling: "1. zwaar; 2. erg, ernstig; 3. streng", repertorium: true, thema: 3, tekst: 1, zin: 10 },
  { grondvorm: "recordari", aanvullingen: "recordor, recordatus sum", vertaling: "zich herinneren, terugdenken aan", thema: 3, tekst: 1, zin: 10 },
  { grondvorm: "inanis", aanvullingen: "inanis, inane", vertaling: "1. leeg, ijl; 2. zinloos", repertorium: true, thema: 3, tekst: 1, zin: 10 },
  { grondvorm: "frigidus", aanvullingen: "frigida, frigidum", vertaling: "koud, koel, kil", repertorium: true, thema: 3, tekst: 1, zin: 10 },
  { grondvorm: "assiduus", aanvullingen: "assidua, assiduum", vertaling: "voortdurend, onafgebroken", thema: 3, tekst: 1, zin: 10 },
  { grondvorm: "insatiabiliter", aanvullingen: "bijw.", vertaling: "onverzadigbaar, niet te verzadigen", thema: 3, tekst: 1, zin: 10 },
  { grondvorm: "desidere", aanvullingen: "desideo, desedi, desessum", vertaling: "stilzitten, lanterfanten", thema: 3, tekst: 1, zin: 11 },
  { grondvorm: "voluptas", aanvullingen: "voluptatis (v.)", vertaling: "genot, genoegen, plezier", repertorium: true, thema: 3, tekst: 1, zin: 11 },
  { grondvorm: "dies", aanvullingen: "diei (m. en v.)", vertaling: "dag", repertorium: true, thema: 3, tekst: 1, zin: 11 },
  { grondvorm: "libenter", aanvullingen: "bijw.", vertaling: "graag, met genoegen", repertorium: true, thema: 3, tekst: 1, zin: 11 },
  { grondvorm: "otium", aanvullingen: "otii (o.)", vertaling: "vrije tijd, nietsdoen, rust", repertorium: true, thema: 3, tekst: 1, zin: 12 },
  { grondvorm: "littera", aanvullingen: "litterae (v.)", vertaling: "1. letter; 2. (mv.) brief, letterkunde", repertorium: true, thema: 3, tekst: 1, zin: 12 },
  { grondvorm: "collocare", aanvullingen: "colloco, collocavi, collocatum", vertaling: "plaatsen, schikken", repertorium: true, thema: 3, tekst: 1, zin: 12 },
  { grondvorm: "otiosus", aanvullingen: "otiosa, otiosum", vertaling: "vrij van zaken, zonder bezigheid, lui", thema: 3, tekst: 1, zin: 12 },
  { grondvorm: "occupatio", aanvullingen: "occupationis (v.)", vertaling: "bezigheid, bezetting", thema: 3, tekst: 1, zin: 12 },
  { grondvorm: "perdere", aanvullingen: "perdo, perdidi, perditum", vertaling: "1. vernietigen; 2. verliezen", repertorium: true, thema: 3, tekst: 1, zin: 12 },

];

// Hulpfuncties
function getByThema(thema) {
  return woordenlijst_3ds.filter(w => w.thema === thema);
}

function getByTekst(thema, tekst) {
  return woordenlijst_3ds.filter(w => w.thema === thema && w.tekst === tekst);
}

function getRepertorium() {
  return woordenlijst_3ds.filter(w => w.repertorium === true);
}
